### ISSUE TITLE
Tablist not working for me

### ISSUE THREAD

**Issue by Spiderjockey02** [montlikadani/TabList#106]
```
[14:42:12 WARN]: java.lang.NullPointerException
[14:42:12 WARN]:        at hu.montlikadani.tablist.Messager.logConsole(Messager.java:15)
[14:42:12 WARN]:        at hu.montlikadani.tablist.Messager.logConsole(Messager.java:11)
[14:42:12 WARN]:        at hu.montlikadani.tablist.Configuration.createFile(Configuration.java:190)
[14:42:12 WARN]:        at hu.montlikadani.tablist.Configuration.loadFiles(Configuration.java:51)
[14:42:12 WARN]:        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:92)
[14:42:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:42:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[14:42:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[14:42:12 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[14:42:12 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[14:42:12 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[14:42:12 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[14:42:12 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[14:42:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:42:12 WARN]: [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues
[14:42:12 WARN]: java.lang.NullPointerException
[14:42:12 WARN]:        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:94)
[14:42:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:42:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[14:42:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[14:42:12 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[14:42:12 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[14:42:12 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[14:42:12 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[14:42:12 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[14:42:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:42:12 WARN]: [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues
```

**Comment by montlikadani** [comment]
Next time paste the error to the code block, also server reload will fix it.

**Comment by montlikadani** [comment]
Fixed in the latest version.
