### ISSUE TITLE
After the v2.4 update, plugin doesn't start

### ISSUE THREAD

**Issue by Cosmunn** [montlikadani/TabList#11]
Can send more info if needed, here's the console log:

[11:25:43] [Server thread/INFO]: [TabList] Enabling TabList v2.4
[11:25:43] [Server thread/INFO]: [TabList] Hooked PlaceholderAPI version: 2.8.5
[11:25:43] [Server thread/WARN]: java.lang.NullPointerException
[11:25:43] [Server thread/WARN]: 	at hu.montlikadani.TabList.TabList.onEnable(TabList.java:106)
[11:25:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:25:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:25:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:25:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
[11:25:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
[11:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[11:25:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:25:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[11:25:43] [Server thread/WARN]: [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues

**Comment by montlikadani** [comment]
@Cosmunn 
Yes, I met this mistake...

**Comment by montlikadani** [comment]
@Cosmunn 
Try a server reload.

**Comment by montlikadani** [comment]
@Cosmunn 
### Thank you for reporting it!
_This issue has been resolved and updated._ https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=218141
