### ISSUE TITLE
Console Report

### ISSUE THREAD

**Issue by sketrick** [montlikadani/TabList#111]
### Describe your problem to what is
Understand what the problem is with the plugin.
Error when closing server
### Details
Plugin version: Latest
Software (Spigot/Bukkit etc.. `/version`) version: 
Paper 1.15.1
### Console error
[04:54:37 INFO]: [TabList] Disabling TabList v5.0
[04:54:37 WARN]: java.lang.NullPointerException
[04:54:37 WARN]:        at hu.montlikadani.tablist.TabList.saveToggledTabs(TabList.java:483)
[04:54:37 WARN]:        at hu.montlikadani.tablist.TabList.onDisable(TabList.java:194)
[04:54:37 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[04:54:37 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[04:54:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
[04:54:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439)
[04:54:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432)
[04:54:37 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:402)
[04:54:37 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:741)
[04:54:37 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:739)
[04:54:37 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:973)
[04:54:37 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by montlikadani** [comment]
Please send the config.yml file.

**Comment by montlikadani** [comment]
Should works in the latest version,
