### ISSUE TITLE
PlayerJoinEvent Error

### ISSUE THREAD

**Issue by FarmVivi** [montlikadani/TabList#112]
### Describe your problem to what is
No TabList after update plugin to 5.0

### Details
Plugin version: 
PaperSpigot 1.12.2 (paper-1618)
TabList v5.0

### Console error
```
[14:24:34 ERROR]: Could not pass event PlayerJoinEvent to TabList v5.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at hu.montlikadani.tablist.TabList.updateTab(TabList.java:578) ~[?:?]
at hu.montlikadani.tablist.Listeners.onPlJoin(Listeners.java:31) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
... 14 more
```

### Configuration file(s)
Send the configuration file(s).
```
https://avadia.fr/download/TabList.rar
```

**Comment by montlikadani** [comment]
Do not close it, will forgot if this closed.

**Comment by FarmVivi** [comment]
I fix the error, I deleted config files and reconfig and it work, it seemed to be located in the tablist.yml file.

**Comment by montlikadani** [comment]
Yea, the in the config tablist is deprecated and will be removed soon, so it is important to move to the new file. Also, there is an NPE check in code, where the section is null, so this is currently a bug.

**Comment by FarmVivi** [comment]
Okay, at least now it's all working.

**Comment by montlikadani** [comment]
Should works in the latest version,
