### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by TheCalypso** [montlikadani/TabList#114]
### Describe your problem to what is
Understand what the problem is with the plugin.
I use the plugin only on the bungeecord (waterfall) and also with the basic config but an error is spammed in the console faster and faster. I don't know what it came from.

### Details
Plugin version: 5.0
Software (Spigot/Bukkit etc.. `/version`) version: Paper1.14.4 #242

### Console error
```
[19:47:57 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@22590e3e, id=21, owner=hu.montlikadani.tablist.bungee.TabList@14168e1, task=hu.montlikadani.tablist.bungee.TabList$2@11181321, delay=0, period=180, running=true) encountered an exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
        at hu.montlikadani.tablist.bungee.TabList.getTablist(TabList.java:242) ~[?:?]
        at hu.montlikadani.tablist.bungee.TabList.access$4(TabList.java:196) ~[?:?]
        at hu.montlikadani.tablist.bungee.TabList$2.run(TabList.java:188) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]

```

### Configuration file(s)
Send the configuration file(s).
```
https://pastebin.com/LHswR2D3
```

### Screenshots (optional)
Send a few pictures about the problem if you can.

Thank you for your help !

**Comment by montlikadani** [comment]
Will be fixed in the next release.

**Comment by montlikadani** [comment]
Should works in the latest version,
