### ISSUE TITLE
Error when disabling and enabling plugin.

### ISSUE THREAD

**Issue by ZandercraftGames** [montlikadani/TabList#118]
### Problem

When disabling/enabling the plugin it throws an error.
### Details
Plugin version: 
v5.1
Software version: 
Paper version git-Paper-112 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
### Console error
```
[17:28:26 INFO]: [TabList] Hooked PlaceholderAPI version: 2.9.2
[17:28:26 WARN]: java.lang.NullPointerException
[17:28:26 WARN]: at hu.montlikadani.tablist.bukkit.TabHandler.loadToggledTabs(TabHandler.java:751)
[17:28:26 WARN]: at hu.montlikadani.tablist.bukkit.TabList.onEnable(TabList.java:107)
[17:28:26 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:28:26 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[17:28:26 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[17:28:26 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[17:28:26 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[17:28:26 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[17:28:26 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[17:28:26 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[17:28:26 WARN]: at java.lang.Thread.run(Thread.java:748)
[17:28:26 WARN]: [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues
```

**Comment by montlikadani** [comment]
Are you deleted the tablist.yml file?

**Comment by ZandercraftGames** [comment]
Just needed to update the config files... They were generated when 1.13.2 was new.
