### ISSUE TITLE
github file missing

### ISSUE THREAD

**Issue by JennerPalacios** [montlikadani/TabList#139]
### Problem

Plugin has version checker, which is looking for file on github, but the file is missing on github

### Details
Plugin version: 
v5.2.1
Software version: 
1.15.2
Relevant plugins: 

### Console error
```
[12:21:58 WARN]: java.io.FileNotFoundException: https://github.com/montlikadani/TabList/releases/download/v5.4.0/TabList.jar
[12:21:58 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[12:21:58 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[12:21:58 WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[12:21:58 WARN]: 	at java.net.URL.openStream(Unknown Source)
[12:21:58 WARN]: 	at hu.montlikadani.tablist.bukkit.utils.UpdateDownloader$1.run(UpdateDownloader.java:88)
[12:21:58 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[12:21:58 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:21:58 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:21:58 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:21:58 WARN]: 	at java.lang.Thread.run(Unknown Source)
```

### Configuration file(s)

config.yml:

**Comment by montlikadani** [comment]
Yea, because it changed the file name to other. So please manually update the plugin now. In the next time you don't need.
