### ISSUE TITLE
Errors In Console

### ISSUE THREAD

**Issue by EgZiG** [montlikadani/TabList#141]
`[10:37:40 WARN]: java.io.IOException: Server returned HTTP response code: 500 for URL: https://github.com/montlikadani/TabList/releases/latest/download/TabList-5.4.0.jar
[10:37:40 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
[10:37:40 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[10:37:40 WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[10:37:40 WARN]: 	at java.net.URL.openStream(URL.java:1045)
[10:37:40 WARN]: 	at hu.montlikadani.tablist.bukkit.utils.UpdateDownloader$1.run(UpdateDownloader.java:101)
[10:37:40 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[10:37:40 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[10:37:40 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:37:40 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:37:40 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:37:40 WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/139
