### ISSUE TITLE
/tl setprefix player 'prefix' destroyed the game

### ISSUE THREAD

**Issue by Temporaly001** [montlikadani/TabList#142]
After messing around /tl setprefix player 'prefix' I made tons of teams that I cannot delete because of disallowed characters like this -> '  And there is no even team with name 1000Administrator, but the plugin still trying to do something with it.

[15:21:43] [Server thread/WARN]: [TabList] Task #57 for TabList v5.3.1 generated an exception
java.lang.IllegalArgumentException: Team name '1000Administrator' is longer than the limit of 16 characters
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:166) ~[spigot
.jar:git-Spigot-800b93f-8160e29]
        at hu.montlikadani.tablist.bukkit.Groups.setPlayerTeam(Groups.java:245) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.setName(Groups.java:205) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.setGroup(Groups.java:168) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.access$2(Groups.java:136) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups$1.run(Groups.java:398) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-800b93f-81
60e29]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot
.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot.jar:git-Spigot-800b93f-816
0e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [spigot.jar:git-Spigot-800b93f-8160
e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot.jar:git-Spigot-800b93f-8160
e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot.jar:git-Spigot-800b93f-81
60e29]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[15:22:13] [Server thread/WARN]: [TabList] Task #57 for TabList v5.3.1 generated an exception
java.lang.IllegalArgumentException: Team name '1000Administrator' is longer than the limit of 16 characters
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:166) ~[spigot
.jar:git-Spigot-800b93f-8160e29]
        at hu.montlikadani.tablist.bukkit.Groups.setPlayerTeam(Groups.java:245) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.setName(Groups.java:205) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.setGroup(Groups.java:168) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.access$2(Groups.java:136) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups$1.run(Groups.java:398) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-800b93f-81
60e29]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot
.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot.jar:git-Spigot-800b93f-816
0e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [spigot.jar:git-Spigot-800b93f-8160
e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot.jar:git-Spigot-800b93f-8160
e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot.jar:git-Spigot-800b93f-81
60e29]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
>

**Comment by montlikadani** [comment]
You using an oldest version of tablist. Please update it first.
