### ISSUE TITLE
Console error when checking for updates

### ISSUE THREAD

**Issue by TarsiSurdi** [montlikadani/TabList#143]
### Problem
Everytime the server is started or reloads its plugins, several warning messages pop up into the console.

### Details
Plugin version: 5.3.1

Software version: Spigot-2040c4c-1872231 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Console error
`
[00:21:20] [Craft Scheduler Thread - 2/WARN]: java.io.FileNotFoundException: https://github.com/montlikadani/TabList/releases/download/v5.4.0/TabList-5.4.0.jar
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at java.net.URL.openStream(Unknown Source)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at hu.montlikadani.tablist.bukkit.utils.UpdateDownloader$1.run(UpdateDownloader.java:101)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[00:21:20] [Craft Scheduler Thread - 2/WARN]:   at java.lang.Thread.run(Unknown Source)
[00:21:20] [Craft Scheduler Thread - 3/INFO]: [Vault] No new version available
`

### Configuration file(s)

config.yml: https://pastebin.com/R9fKB6S7

**Comment by TarsiSurdi** [comment]
When modifying the **"download-updates"** setting to **false** the error goes away.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/139#issuecomment-624259790
