### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by BraveBurster** [montlikadani/TabList#15]
Hi, i'm using craftbukkit 1.8.8, and i keep getting 1 error on my console:
```
13.04 11:55:01 [Server] WARN java.lang.NoSuchFieldException: recentTps
13.04 11:55:01 [Server] WARN at java.lang.Class.getField(Class.java:1703)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList.getTps(TabList.java:736)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList.replaceVariables(TabList.java:679)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList$8.run(TabList.java:617)
13.04 11:55:01 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
13.04 11:55:01 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
13.04 11:55:01 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13.04 11:55:01 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13.04 11:55:01 [Server] WARN at java.lang.Thread.run(Thread.java:748)
13.04 11:55:01 [Server] WARN java.lang.NoSuchFieldException: recentTps
13.04 11:55:01 [Server] WARN at java.lang.Class.getField(Class.java:1703)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList.getTps(TabList.java:736)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList.replaceVariables(TabList.java:679)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList$8.run(TabList.java:617)
13.04 11:55:01 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
13.04 11:55:01 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
13.04 11:55:01 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13.04 11:55:01 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13.04 11:55:01 [Server] WARN at java.lang.Thread.run(Thread.java:748)
13.04 11:55:01 [Server] WARN java.lang.NoSuchFieldException: recentTps
13.04 11:55:01 [Server] WARN at java.lang.Class.getField(Class.java:1703)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList.getTps(TabList.java:736)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList.replaceVariables(TabList.java:679)
13.04 11:55:01 [Server] WARN at hu.montlikadani.TabList.TabList$8.run(TabList.java:617)
13.04 11:55:01 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
13.04 11:55:02 [Multicraft] Skipped 14 lines due to rate limit (30/s)
13.04 11:55:02 [Server] WARN java.lang.NoSuchFieldException: recentTps
13.04 11:55:02 [Server] WARN at java.lang.Class.getField(Class.java:1703)
13.04 11:55:02 [Server] WARN at hu.montlikadani.TabList.TabList.getTps(TabList.java:736)
13.04 11:55:02 [Server] WARN at hu.montlikadani.TabList.TabList.replaceVariables(TabList.java:679)
13.04 11:55:02 [Server] WARN at hu.montlikadani.TabList.TabList$8.run(TabList.java:617)
13.04 11:55:02 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
13.04 11:55:02 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
13.04 11:55:02 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13.04 11:55:02 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13.04 11:55:02 [Server] WARN at java.lang.Thread.run(Thread.java:748)
13.04 11:55:02 [Server] WARN java.lang.NoSuchFieldException: recentTps
13.04 11:55:02 [Server] WARN at java.lang.Class.getField(Class.java:1703)
13.04 11:55:02 [Server] WARN at hu.montlikadani.TabList.TabList.getTps(TabList.java:736)
13.04 11:55:02 [Server] WARN at hu.montlikadani.TabList.TabList.replaceVariables(TabList.java:679)
13.04 11:55:02 [Server] WARN at hu.montlikadani.TabList.TabList$8.run(TabList.java:617)
13.04 11:55:02 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
13.04 11:55:02 [Server] WARN at 
```

**Comment by BraveBurster** [comment]
Well i switched to spigot and now it works fine ;)

**Comment by montlikadani** [comment]
No problem. This is an error that does not work with the CraftBukkit version.

**Comment by montlikadani** [comment]
For now, %tps% placeholder will not work on CraftBukkit versions. So this long console error does not send.

**Comment by montlikadani** [comment]
CraftBukkit versions is outdated thing. I recommend you to update at least to Spigot which is supported and also had `recentTps` field and plugin can retrieve tps value from server. This issue never get fix in the future, but this error never pops up. The tps value always being 20.0 on CB versions.
