### ISSUE TITLE
Updater exception

### ISSUE THREAD

**Issue by Maathias** [montlikadani/TabList#164]
### Problem

If the updater is enabled, for every reload this exception throws

### Details
Plugin version: v5.2.1

Software version: 1.16.1

### Console error
```
[16:37:27] [Craft Scheduler Thread - 2/WARN]: java.io.FileNotFoundException: https://github.com/montlikadani/TabList/releases/download/v5.4.5/TabList.jar       
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)                     
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)                      
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)            
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at java.net.URL.openStream(URL.java:1068)                                                                       
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at hu.montlikadani.tablist.bukkit.utils.UpdateDownloader$1.run(UpdateDownloader.java:88)                        
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81)                                   
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)                         
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                              
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                              
[16:37:27] [Craft Scheduler Thread - 2/WARN]:   at java.lang.Thread.run(Thread.java:748)
```

**Comment by montlikadani** [comment]
You have to manually update the tablist, because there are some changes in updater, so it will breaks, because there is a file name change or something else.
