### ISSUE TITLE
/tablist reload error

### ISSUE THREAD

**Issue by Zakkary19** [montlikadani/TabList#165]
### Problem

I reloaded the plugin (/tablist reload) and it gives me this error.

### Details
Plugin version: 
Tablist version 5.4.5

Software version: 
Paper version git-Paper-130 (MC 1.16.1)

Relevant plugins: 

### Console error
```
issued server command: /tablist reload
>.... [19:59:41 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tablist' in plugin TabList v5.4.5
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-130]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-130]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-130]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-130]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
at hu.montlikadani.tablist.bukkit.Groups.load(Groups.java:71) ~[?:?]
at hu.montlikadani.tablist.bukkit.TabList.reload(TabList.java:242) ~[?:?]
at hu.montlikadani.tablist.bukkit.commands.list.reload.run(reload.java:22) ~[?:?]
at hu.montlikadani.tablist.bukkit.commands.Commands.onCommand(Commands.java:84) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-130]
... 18 more
```

### Configuration file(s)

configuration file: 
https://pastebin.com/yeCqxJ6T -- tablist.yml
https://pastebin.com/rtin0mLK - config.yml

**Comment by montlikadani** [comment]
You were removed the groups section from groups.yml file. Don't modify if you don't know what you're doing.

**Comment by Zakkary19** [comment]
Oh okay, I have never touched the groups.yml file so I am not sure how that would have been removed.
