### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ryuryu10** [montlikadani/TabList#170]
[12:40:49 WARN]: [TabList] Plugin TabList v5.4.6 generated an exception while executing task 556
java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission
        at hu.montlikadani.tablist.bukkit.TabListPlayer.lambda$2(TabListPlayer.java:126) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_261]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261]
        at hu.montlikadani.tablist.bukkit.TabListPlayer.update(TabListPlayer.java:127) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.updatePlayers(Groups.java:259) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.lambda$2(Groups.java:244) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by ryuryu10** [comment]
[12:41:52 WARN]: [TabList] Plugin TabList v5.4.6 generated an exception while executing task 556
java.lang.NullPointerException: null
        at hu.montlikadani.tablist.bukkit.TabListPlayer.lambda$2(TabListPlayer.java:126) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_261]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261]
        at hu.montlikadani.tablist.bukkit.TabListPlayer.update(TabListPlayer.java:127) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.updatePlayers(Groups.java:259) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.lambda$2(Groups.java:244) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by ryuryu10** [comment]
[12:41:52 INFO]: This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[12:41:52 INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.

**Comment by montlikadani** [comment]
You don't have Vault installed.

**Comment by ryuryu10** [comment]
[17:29:53 WARN]: [TabList] Plugin TabList v5.4.6 generated an exception while executing task 42374
java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:100) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
        at hu.montlikadani.tablist.bukkit.TabListPlayer.lambda$1(TabListPlayer.java:122) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_261]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261]
        at hu.montlikadani.tablist.bukkit.TabListPlayer.update(TabListPlayer.java:123) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.updatePlayers(Groups.java:259) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.lambda$2(Groups.java:244) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[1.12.2.jar:git-Bukkit-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [1.12.2.jar:git-Bukkit-acbc348]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by montlikadani** [comment]
Now you don't have any permission plugin. Install one

**Comment by ryuryu10** [comment]
Which plugin should I install?

**Comment by montlikadani** [comment]
LuckPerms better

**Comment by ryuryu10** [comment]
Okay, I'll try

**Comment by ryuryu10** [comment]
Thank you.
I can't find any more errors on the console.
