### ISSUE TITLE
Exceptions | java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission

### ISSUE THREAD

**Issue by MikronT** [montlikadani/TabList#173]
### Problem

Many exception messages in the console log

### Details
Plugin version: 5.4.6 (latest)

Software version: Paper 1.16.2

Relevant plugins: nothing

### Console error
```
java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission
        at hu.montlikadani.tablist.bukkit.TabListPlayer.lambda$2(TabListPlayer.java:126) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_261]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261]
        at hu.montlikadani.tablist.bukkit.TabListPlayer.update(TabListPlayer.java:127) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.updatePlayers(Groups.java:259) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.lambda$2(Groups.java:244) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-178]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-178]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-178]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

### Configuration file(s)

configuration file: 

The exception appears even with the generated config files

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/45333177/92138694-5f5fe500-ee17-11ea-89f6-e964ed395019.png)

**Comment by montlikadani** [comment]
You don't have Vault installed.

**Comment by MikronT** [comment]
All the messages are **always the same**

**Comment by MikronT** [comment]
A new dependency?

**Comment by montlikadani** [comment]
> A new dependency?

wat, its already been a softdependency, just have some problems when comparing group names.

In this case you can download a fixed dev-version from https://github.com/montlikadani/TabList/actions/runs/236405306 (find artifacts)

**Comment by MikronT** [comment]
Thank you very much for your help
