### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by LevM-A** [montlikadani/TabList#174]
### Problem

TabList
### Details
Plugin version:  v5.4.6

Software version: Paper 1.16.2

Relevant plugins:  AuthMe, Chatty, CoreProtect, CoreProtectTNT, DiscordWhitelister, Easywhitelist, EntityTracherFixer, LuckPerms, MOTD, PL-Hide, PlaceholderAPI, SmoothSleep, TabList

### Console error
```
Send the console error if you have it.
```
[10:00:06 WARN]: [TabList] Plugin TabList v5.4.6 generated an exception while executing task 8420
java.lang.NullPointerException: null
        at hu.montlikadani.tablist.bukkit.TabListPlayer.lambda$2(TabListPlayer.java:126) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_111]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_111]
        at hu.montlikadani.tablist.bukkit.TabListPlayer.update(TabListPlayer.java:127) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.updatePlayers(Groups.java:259) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.lambda$2(Groups.java:244) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-162]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
### Configuration file(s)

configuration file: https://pastebin.com/V8Byj8jH

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/170
