### ISSUE TITLE
Console Warn Spam on Paper

### ISSUE THREAD

**Issue by S0LDR** [montlikadani/TabList#175]
Plugin version: v5.4.6

Software version: Paper (latest 1.12.2)

```
[17:12:47 WARN]: [TabList] Plugin TabList v5.4.6 generated an exception while executing task 161
java.lang.NullPointerException: null
        at hu.montlikadani.tablist.bukkit.TabListPlayer.lambda$2(TabListPlayer.java:126) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_265]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_265]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_265]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_265]
        at hu.montlikadani.tablist.bukkit.TabListPlayer.update(TabListPlayer.java:127) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.updatePlayers(Groups.java:259) ~[?:?]
        at hu.montlikadani.tablist.bukkit.Groups.lambda$2(Groups.java:244) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1589]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1589]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

```

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/174
