### ISSUE TITLE
Could Not Pass Event PlayerJoinEvent

### ISSUE THREAD

**Issue by Ekpoa** [montlikadani/TabList#186]
### Problem
Dont work

### Details
Plugin version: 
latest

### Console error
```
[17:04:27 ERROR]: Could not pass event PlayerJoinEvent to TabList v5.4.8
java.lang.NullPointerException: null
        at hu.montlikadani.tablist.bukkit.tablist.TabHandler.updateTab(TabHandler.java:174) ~[?:?]
        at hu.montlikadani.tablist.bukkit.tablist.TabManager.addPlayer(TabManager.java:41) ~[?:?]
        at hu.montlikadani.tablist.bukkit.TabList.updateAll(TabList.java:353) ~[?:?]
        at hu.montlikadani.tablist.bukkit.TabList.updateAll(TabList.java:296) ~[?:?]
        at hu.montlikadani.tablist.bukkit.listeners.Listeners.onPlJoin(Listeners.java:29) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor408.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-231]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-231]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-231]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-231]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

### Configuration file(s)

Default

**Comment by montlikadani** [comment]
You can download [here](https://github.com/montlikadani/TabList/actions/runs/310569511) the fixed version.
