### ISSUE TITLE
TPS displaying issue

### ISSUE THREAD

**Issue by X12503181** [montlikadani/TabList#187]
### Problem

In `config.yml`:

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 20.14
    size: 3

Setting the `size` value to 4 or higher will result in the TPS not displaying correctly and constantly throwing error messages in the console. *Also, the new tps color format description is rather confusing as the default preset format is wrong (which always gives you a red color when the tps is above 16).* 

### Details
Plugin version: 5.4.8

Software version: Paper-256 ~ Paper-259 (Minecraft 1.16.4)

Before upgrading to Minecraft 1.16.4, I was using TabList 5.4.4, which works fine when the `size` was set to 4, so I'm not sure whether this bug is caused by the by the plugin itself or the server software.

### Console error

Note: these errors generate only when at least one player is in the server.

```
[TabList] Plugin TabList v5.4.8 generated an exception while executing task 5733
java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0_265]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_265]
        at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_265]
        at hu.montlikadani.tablist.bukkit.utils.operators.OperatorNodes.parse(OperatorNodes.java:111) ~[?:?]
        at hu.montlikadani.tablist.bukkit.utils.Variables.parseExpression(Variables.java:297) ~[?:?]
        at hu.montlikadani.tablist.bukkit.utils.Variables.formatTPS(Variables.java:290) ~[?:?]
        at hu.montlikadani.tablist.bukkit.utils.Variables.tpsDot(Variables.java:268) ~[?:?]
        at hu.montlikadani.tablist.bukkit.utils.Variables.replaceVariables(Variables.java:213) ~[?:?]
        at hu.montlikadani.tablist.bukkit.tablist.TabHandler.sendTab(TabHandler.java:277) ~[?:?]
        at hu.montlikadani.tablist.bukkit.tablist.TabHandler.lambda$0(TabHandler.java:209) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-256]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-256]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-256]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

### Configuration file(s)

configuration file: `config.yml`

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 20.14
    size: 4

**Comment by TheNety** [comment]
Hey, can confirm the error with size 4, the color also isn't correct in latest github dev-build + it's going in wrong line. Video: https://i.imgur.com/5ko4tje.mp4
```      
    formats:
    - 18.0 > &a
    - 16.0 == &6
    - 16.0 < &c
```

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/1dcd7991dc4acdb10e3fd52d5126dc1a043a5d1d
https://github.com/montlikadani/TabList/actions/runs/344300627
