### ISSUE TITLE
no color

### ISSUE THREAD

**Issue by MoonVN571** [montlikadani/TabList#193]
i cant see color on footer tablist

### Details
Plugin version: 
5.5.0 (i have download latest)

Software version: 
Paper Spigot

Relevant plugins: 

### Console error
```
Send the console error if you have it.
```
[15:59:20 WARN]: [TabList] Plugin TabList v5.5.0 generated an exception while ex
ecuting task 182
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_251
]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_251]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_251]
        at hu.montlikadani.tablist.bukkit.tablist.TabManager.lambda$0(TabManager
.java:71) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_251]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

### Configuration file(s)

https://pastebin.com/JtWbk2cM

configuration file: 

https://pastebin.com/n0fjGWvj

### Screenshots (optional)

https://imgur.com/a/2ndI8H4

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/actions/runs/400360714
Fixed in this version. See Artifacts
