### ISSUE TITLE
I have some warning in my Console

### ISSUE THREAD

**Issue by Flearl** [montlikadani/TabList#198]
### Details
Plugin version: 

Software version: 

Relevant plugins: 

 Console error
[16:25:53 WARN]: java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabList/master/src/main/resources/plugin.yml
[16:25:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
[16:25:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[16:25:53 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[16:25:53 WARN]:        at java.base/java.net.URL.openStream(URL.java:1140)
[16:25:53 WARN]:        at hu.montlikadani.tablist.bukkit.utils.UpdateDownloader.lambda$0(UpdateDownloader.java:31)
[16:25:53 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[16:25:53 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
[16:25:53 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[16:25:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[16:25:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[16:25:53 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[16:25:53 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Insert here the console error if you have it.
```

### Configuration file(s)
<!--Insert here the configuration file(s) to [pastebin.com](pastebin.com) or [hastebin.com](hastebin.com) or to other sites.-->
configuration file: 

### Screenshots (optional)
<!--Send a few pictures about the problem if you can.-->

**Comment by Flearl** [comment]
This warning is coming when player join the server

**Comment by montlikadani** [comment]
Disable update check in config, https://github.com/montlikadani/TabList/blob/83dfc3751c159d694c3d1329cdbd75dcb09bfc93/bukkit/src/main/resources/config.yml#L237

**Comment by Flearl** [comment]
Thaks for the fast answer
It has work and the warning dont come again

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: montlikadani<mailto:notifications@github.com>
Gesendet: Mittwoch, 30. Dezember 2020 16:35
An: montlikadani/TabList<mailto:TabList@noreply.github.com>
Cc: Flearl<mailto:florian_ebert96@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [montlikadani/TabList] I have some warning in my Console (#198)


Disable update check in config, https://github.com/montlikadani/TabList/blob/83dfc3751c159d694c3d1329cdbd75dcb09bfc93/bukkit/src/main/resources/config.yml#L237<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmontlikadani%2FTabList%2Fblob%2F83dfc3751c159d694c3d1329cdbd75dcb09bfc93%2Fbukkit%2Fsrc%2Fmain%2Fresources%2Fconfig.yml%23L237&data=04%7C01%7C%7Ce22509776aec49ae8b7d08d8acd8896a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637449393299118046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iY0PDGB8mtn5X%2BUBG2R%2FnxYQjagFg%2FzVCK05Rc38auo%3D&reserved=0>
