### ISSUE TITLE
FileNotFoundException looking for plugin.yml

### ISSUE THREAD

**Issue by shimajima** [montlikadani/TabList#200]
### Details
Plugin version: 5.5.0

Software version: git-Paper-344 (MC: 1.16.4)

Relevant plugins: TabList 5.5.0

### Console error
```
java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabList/master/src/main/resources/plugin.yml
       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
       at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
       at java.net.URL.openStream(Unknown Source)
       at hu.montlikadani.tablist.bukkit.utils.UpdateDownloader.lambda$0(UpdateDownloader.java:31)
       at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
       at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
       at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
       at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
       at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

### Configuration file(s)

configuration file:

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/198#issuecomment-752664173

**Comment by shimajima** [comment]
Disabled check for updates fixed it! Thank you!
