### ISSUE TITLE
(1.16.4) NPE spam in client log

### ISSUE THREAD

**Issue by X12503181** [montlikadani/TabList#205]
### Problem

Tested on several different Windows/Linux Paper servers (both Java 8, 11) with TabList and Windows/Linux/MacOS clients (also both Java 8, 11). All with the same problem and this is clogging up the log files - the same error messages are being thrown in the log several times within a second as long as the client is connected to the server and usually gives more than 1 MB of log files if played for some time (more than 10 MB if played for hours).

This does not interfere with game perfomance. It runs normally but the launcher crashes when trying to view the log.

### Details

***Only occurs with Minecraft 1.16.4.***

Plugin version: 5.4.4 ~ 5.5.1
I was using 5.4.4 when I updated my own server to 1.16.4 ~2 months ago (and have updated the server/plugin many times after that). Every single log file since then was filled with those error messages (also happens on other servers with this plugin).

Software version: since Paper-256 (first 1.16.4 build)

Relevant plugins: only with this plugin is enough to produce the bug.

### Client error log

Official launcher (1.16.4 vanilla):

```
[Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at dwu.a(SourceFile:2128) ~[1.16.4.jar:?]
	at ri.a(SourceFile:122) ~[1.16.4.jar:?]
	at ri.a(SourceFile:16) ~[1.16.4.jar:?]
	at ol.a(SourceFile:21) ~[1.16.4.jar:?]
	at aob.c(SourceFile:144) [1.16.4.jar:?]
	at aof.c(SourceFile:23) [1.16.4.jar:?]
	at aob.y(SourceFile:118) [1.16.4.jar:?]
	at aob.bl(SourceFile:103) [1.16.4.jar:?]
	at djz.e(SourceFile:1015) [1.16.4.jar:?]
	at djz.e(SourceFile:681) [1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [1.16.4.jar:?]
```

MultiMC (1.16.4 vanilla):

```
[Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at dwu.a(SourceFile:2128) ~[minecraft-1.16.4-client.jar:?]
	at ri.a(SourceFile:122) ~[minecraft-1.16.4-client.jar:?]
	at ri.a(SourceFile:16) ~[minecraft-1.16.4-client.jar:?]
	at ol.a(SourceFile:21) ~[minecraft-1.16.4-client.jar:?]
	at aob.c(SourceFile:144) [minecraft-1.16.4-client.jar:?]
	at aof.c(SourceFile:23) [minecraft-1.16.4-client.jar:?]
	at aob.y(SourceFile:118) [minecraft-1.16.4-client.jar:?]
	at aob.bl(SourceFile:103) [minecraft-1.16.4-client.jar:?]
	at djz.e(SourceFile:1015) [minecraft-1.16.4-client.jar:?]
	at djz.e(SourceFile:681) [minecraft-1.16.4-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [minecraft-1.16.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

### Configuration file(s)

configuration file: 
Use the default config. This bug persists after upgrading the server software and plugin and reseting all configs.

### Screenshots (optional)

![20210108213839](https://user-images.githubusercontent.com/17661805/104027464-643c0780-5202-11eb-8121-111c55fccf1b.png)

**Comment by montlikadani** [comment]
> Software version: since Paper-256 (first 1.16.4 build)

It is time to update your server software first time, because for me this can't reproducible.

**Comment by TheNety** [comment]
So after some testing I could reproduce that in versions v5.4.8 - v5.5.1. The latest unaffected version is v5.4.7.

**Comment by X12503181** [comment]
> > Software version: since Paper-256 (first 1.16.4 build)
> 
> It is time to update your server software first time, because for me this can't reproducible. Now I tested on Java 8, 15, 11, with 1.16.4 launcher and server. It worked.

I mean I first encountered this bug with that version (the latest version when I updated to 1.16.4 in Nov) and it keeps happening every later version (I update the software somewhat frequently and by now it's already newest version). All Paper builds after Paper 256 are affected (I didn't test Spigot itself yet).

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/9c57ea4e40f4b50dc7b82864d4aac0641432eb21

To download, click on the first action and find artifacts -> download: https://github.com/montlikadani/TabList/actions
