### ISSUE TITLE
Nullpointer on version check

### ISSUE THREAD

**Issue by madmagic007** [montlikadani/TabList#209]
### Problem

On plugin enabling, it throws nullpointer exception on what i believe is version check

### Details
Plugin version:  5.4.0

Software: Paper version: 454

Relevant plugins: 

### Console error
```
     java.lang.NullPointerException
     	at hu.montlikadani.tablist.bukkit.utils.ServerVersion$Version.isCurrentLower(ServerVersion.java:91)
     	at hu.montlikadani.tablist.bukkit.TabList.onEnable(TabList.java:80)
     	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
     	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
     	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
     	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
     	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
     	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464)
     	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
     	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)
     	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
     	at java.lang.Thread.run(Unknown Source)
```

### Configuration file(s)

configuration file: 
the plugin is fresly installed so i assume this is irrelevant

**Comment by montlikadani** [comment]
> Plugin version: 5.4.0

You uses old version

**Comment by madmagic007** [comment]
yes sorry i somehiw downloaded an outdated version. its fixed now
