### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by Rollczi** [montlikadani/TabList#210]
### Problem
Error

### Details
Plugin version: 5.5.2

Software version: 1.12.2

### Console error
```

[09:17:57 WARN]: [TabList] Plugin TabList v5.5.2 generated an exception while executing task 49657
java.lang.NullPointerException: null
        at hu.montlikadani.tablist.bukkit.Groups.lambda$startTask$0(Groups.java:264) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1618]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1618]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

```

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/a12546bbd6690496626588bda53294229961a063
