### ISSUE TITLE
KICK PLAYER RANDOMLY

### ISSUE THREAD

**Issue by Kr1S-D** [montlikadani/TabList#228]
For some absurd reason ... your plugin kicks players on my server, here is the error it gives

`[14:22:03] [Craft Scheduler Thread - 5219/WARN]: [TabList] Plugin TabList v5.5.2 generated an exception while executing task 476945
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:97) ~[patched_1.12.2.jar:git-Paper-1618]
	at hu.montlikadani.tablist.bukkit.Objects.lambda$null$2(Objects.java:140) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_282]
	at hu.montlikadani.tablist.bukkit.Objects.lambda$startTask$3(Objects.java:133) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`

**Comment by montlikadani** [comment]
You can use the [development release](https://github.com/montlikadani/TabList/actions/runs/735523615), find under Artifacts, install and let us know the issue is still persist.

**Comment by Kr1S-D** [comment]
nothig changed

**Comment by montlikadani** [comment]
Send the new error

**Comment by Kr1S-D** [comment]
This does not really create the tab ... But I always kika people without launching exemptions, cmq if I remove it this does not happen anymore

**Comment by montlikadani** [comment]
> 
> 
> Send the new error

^ send this not the result of what happens

**Comment by Kr1S-D** [comment]
```
[13:40:10] [Craft Scheduler Thread - 116502/WARN]: [TabList] Plugin TabList v5.5.2 generated an exception while executing task 13215160
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:97) ~[patched_1.12.2.jar:git-Paper-1618]
	at hu.montlikadani.tablist.bukkit.Objects.lambda$null$2(Objects.java:140) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_282]
	at hu.montlikadani.tablist.bukkit.Objects.lambda$startTask$3(Objects.java:133) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
	
	[13:40:13] [Server thread/INFO]: [-] Danizyo
[13:40:13] [Server thread/INFO]: Spinjitzu_ lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player Spinjitzu_ orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] Autorizzazione temporanea essentials.fly non impostata per Spinjitzu_ nel contesto global.
[13:40:13] [Server thread/INFO]: [-] Spinjitzu_
[13:40:13] [Server thread/INFO]: Faricon371 lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player Faricon371 orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] Faricon371 non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] Faricon371
[13:40:13] [Server thread/INFO]: Dio_Is_Here lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player Dio_Is_Here orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] Autorizzazione temporanea essentials.fly non impostata per Dio_Is_Here nel contesto global.
[13:40:13] [Server thread/INFO]: [-] Dio_Is_Here
[13:40:13] [Server thread/INFO]: NotGinco lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player NotGinco orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] NotGinco non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] NotGinco
[13:40:13] [Server thread/INFO]: Curdur lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player Curdur orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] Curdur non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] Curdur
[13:40:13] [Server thread/INFO]: BloodlineVI lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player BloodlineVI orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] BloodlineVI non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] BloodlineVI
[13:40:13] [Server thread/INFO]: paki1926 lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player paki1926 orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] paki1926 non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] paki1926
[13:40:13] [Server thread/INFO]: 3ndrygamer lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player 3ndrygamer orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] 3ndrygamer non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] 3ndrygamer
[13:40:13] [Server thread/INFO]: ImDoddoh lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player ImDoddoh orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] ImDoddoh non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] ImDoddoh
[13:40:13] [Server thread/INFO]: 777EzAred777 lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player 777EzAred777 orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] 777EzAred777 non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] 777EzAred777
[13:40:13] [Server thread/INFO]: Xx_David007_xX lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player Xx_David007_xX orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] Xx_David007_xX non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] Xx_David007_xX
[13:40:13] [Server thread/INFO]: zNicoh_ lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player zNicoh_ orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] zNicoh_ non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] zNicoh_
[13:40:13] [Server thread/INFO]: zGiangio14 lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player zGiangio14 orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] zGiangio14 non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] zGiangio14
[13:40:13] [Server thread/INFO]: zAle73_ lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player zAle73_ orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] zAle73_ non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] zAle73_
[13:40:13] [Server thread/INFO]: Kr1S_D lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: Il Player Kr1S_D orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [Server thread/INFO]: Il Player Kr1S_D e' oppato, orcoddio lo deoppo
[13:40:13] [pool-10-thread-1/INFO]: [LP] Kr1S_D non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] Kr1S_D
[13:40:13] [Server thread/INFO]: MIRKOTODINI lost connection: Disconnected
[13:40:13] [Server thread/INFO]: Il Player MIRKOTODINI orcoddio che cazzo bugabusi... 
[13:40:13] [Server thread/INFO]: Resettando il permesso essentials.fly :-) 
[13:40:13] [pool-10-thread-1/INFO]: [LP] MIRKOTODINI non ha essentials.fly impostato nel contesto global.
[13:40:13] [Server thread/INFO]: [-] MIRKOTODINI
[13:40:13] [Server thread/INFO]: Fl3sty005 lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: [-] Fl3sty005
[13:40:13] [Server thread/INFO]: SimplyGias lost connection: Internal Exception: java.io.IOException: Connection reset by peer
[13:40:13] [Server thread/INFO]: [-] SimplyGias
```

**Comment by montlikadani** [comment]
You did not even replaced the old jar with the new that I sent before.

**Comment by Kr1S-D** [comment]
I told you, that with the old man it does nothing but kikc the same ...

**Comment by Kr1S-D** [comment]
I thought you were asking me for the previous error

**Comment by rhystedstone** [comment]
I'd suggest waiting for the problem to occur again, then checking to see if tablist caused it. It doesn't seem like the plugin would've caused the "java.io.IOException: Connection reset by peer".
It's most likely a plugin which handles how players connect, such as ViaVersion, or a network thing.

**Comment by montlikadani** [comment]
Check the new update
