### ISSUE TITLE
NPE Player leave & no color

### ISSUE THREAD

**Issue by Fonkio** [montlikadani/TabList#234]
### Problem

NPE spam in chat when player in the group named "BuilderVipGold" leave the server
Now when this player join, he have no color
### Details
Plugin version: 
5.5.3
Software version: 
git-Paper-566
Relevant plugins: 
* GroupManager
### Console error
```
[10:36:54] [Server thread/INFO]: XWan_RX lost connection: Disconnected
[10:36:55] [Craft Scheduler Thread - 833/WARN]: java.lang.NullPointerException
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:106)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:98)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.getHandle(ReflectionUtils.java:80)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:42)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:80)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:36:55] [Craft Scheduler Thread - 833/WARN]: [TabList] Plugin TabList v5.5.3 generated an exception while executing task 163708
java.lang.NullPointerException: null
	at hu.montlikadani.tablist.bukkit.tablist.groups.GroupPlayer.getCustomTabName(GroupPlayer.java:299) ~[?:?]
	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:107) ~[?:?]
	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:81) ~[?:?]
	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159) ~[?:?]
	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306) ~[?:?]
	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266) ~[?:?]
	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-566]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-566]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-566]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

... 
```

### Configuration file(s)

[config.yml](https://code.alwyn974.re/jewebidaxo)
[groups.yml](https://code.alwyn974.re/azedeyaqig)
[tablist.yml](https://code.alwyn974.re/xoqeqoticu)
### Screenshots (optional)

![image](https://user-images.githubusercontent.com/28084726/116816838-eb234000-ab63-11eb-923a-d8c4d5237d29.png)

**Comment by montlikadani** [comment]
You can use the newest build from [here](https://github.com/montlikadani/TabList/actions/runs/804071104) to fix this.

**Comment by montlikadani** [comment]
You can install the newest build from [here](https://github.com/montlikadani/TabList/actions/runs/804490050) to fix this issue.

**Comment by Fonkio** [comment]
Hi,
My problem has not been solved with this new build

**Comment by montlikadani** [comment]
Which problem?

**Comment by Fonkio** [comment]
Sometimes, when a player disconnects from the server this error appears every 5 seconds
``refresh-interval: 100``
5 sec = 100 / 20
Error :
```
[20:32:50 INFO]: Fonkio_ lost connection: Disconnected
[20:32:50 WARN]: java.lang.NullPointerException
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:103)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:95)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.getHandle(ReflectionUtils.java:77)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:42)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:80)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[20:32:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:32:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:32:50 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:32:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:32:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:32:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[20:32:50 WARN]: java.lang.NullPointerException
[20:32:50 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[20:32:50 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)
[20:32:50 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:780)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:144)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:81)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[20:32:50 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[20:32:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:32:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:32:50 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:32:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:32:50 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:32:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[20:32:55 WARN]: java.lang.NullPointerException
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:103)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:95)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.getHandle(ReflectionUtils.java:77)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:42)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:80)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[20:32:55 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[20:32:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:32:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:32:55 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:32:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:32:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:32:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[20:32:55 WARN]: java.lang.NullPointerException
[20:32:55 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[20:32:55 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)```

**Comment by Fonkio** [comment]
After that if the player reconnects, the error doesn't appear anymore but the player remains in white in the tab
![image](https://user-images.githubusercontent.com/28084726/116919639-d7560780-ac51-11eb-911b-7f7e9447ec19.png)

**Comment by montlikadani** [comment]
Seems to be a new error, I've fixed this now. You can try again with [this](https://github.com/montlikadani/TabList/actions/runs/807825669) build.

**Comment by Fonkio** [comment]
Ok I'll try thanks

**Comment by Fonkio** [comment]
Hi again ! problem still not solved with this new build :/

**Comment by montlikadani** [comment]
Is the error gone?

**Comment by Fonkio** [comment]
No

**Comment by montlikadani** [comment]
Well, you probably installed the one that built yesterday, I made a new one and these errors have already been fixed.

**Comment by Fonkio** [comment]
Now it's on player join I don't know if it makes a difference:
```
[23:45:02] [Server thread/INFO]: [+] LoulixFR a rejoint MvWild.
[23:45:07] [Craft Scheduler Thread - 73/WARN]: java.lang.NullPointerException
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:780)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:144)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:85)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[23:45:07] [Craft Scheduler Thread - 73/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: java.lang.NullPointerException
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:780)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:144)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:85)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[23:45:12] [Craft Scheduler Thread - 74/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:45:16] [Craft Scheduler Thread - 73/INFO]: [AuthMe] LoulixFR logged in 78.XXX.X.XXX
[23:45:17] [Craft Scheduler Thread - 78/WARN]: java.lang.NullPointerException
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:780)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:144)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:85)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[23:45:17] [Craft Scheduler Thread - 78/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: java.lang.NullPointerException
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:780)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:144)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:85)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.setPlayerTeam(Groups.java:159)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.sortScoreboards(Groups.java:306)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.updatePlayers(Groups.java:266)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.Groups.lambda$startTask$0(Groups.java:251)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[23:45:22] [Craft Scheduler Thread - 66/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by montlikadani** [comment]
Yes, you have the old, you need the newest one.

**Comment by Fonkio** [comment]
Same link ?

**Comment by montlikadani** [comment]
No, here: https://github.com/montlikadani/TabList/actions/runs/810023905

**Comment by Fonkio** [comment]
Ok thanks ! I'll try and let you know if it works
