### ISSUE TITLE
Prefix and Suffix not showing up

### ISSUE THREAD

**Issue by PlaceblockHD** [montlikadani/TabList#235]
Hey! I cant see the Prefix and Suffix of players in the tablist... i am using vault + luckperms.

There is also an error when a player joins first time after reload:

`[17:38:38 WARN]: java.lang.NoSuchMethodException: java.lang.Class.getDeclaredFieldsImpl()

[17:38:38 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2633)

[17:38:38 WARN]:        at hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.<clinit>(ReflectionUtils.java:43)

[17:38:38 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.TabTitle.<clinit>(TabTitle.java:15)

[17:38:38 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.TabHandler.updateTab(TabHandler.java:51)

[17:38:38 WARN]:        at hu.montlikadani.tablist.bukkit.tablist.TabManager.addPlayer(TabManager.java:45)

[17:38:38 WARN]:        at hu.montlikadani.tablist.bukkit.TabList.updateAll(TabList.java:327)

[17:38:38 WARN]:        at hu.montlikadani.tablist.bukkit.TabList.updateAll(TabList.java:284)

[17:38:38 WARN]:        at hu.montlikadani.tablist.bukkit.listeners.Listeners.lambda$onPlJoin$0(Listeners.java:32)

[17:38:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)

[17:38:38 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)

[17:38:38 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)

[17:38:38 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)

[17:38:38 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)

[17:38:38 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)

[17:38:38 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

I am using Java 15, if this is important...
Maybe you can help me : )

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/1db3afb2ad865a2f166a14a2e52c6a4173eb5d49

This error is been fixed now with the above commit. You can install the newest build from [here](https://github.com/montlikadani/TabList/actions/runs/804582585) under Artifacts.
