### ISSUE TITLE
The tablist is completely gone 

### ISSUE THREAD

**Issue by toby-ger** [montlikadani/TabList#244]
Die Tablist ist komplett weg ?

![2021-06-12_01 23 42](https://user-images.githubusercontent.com/71409069/121757150-e1a2d580-cb1c-11eb-931b-3ed9781819ed.png)

[00:36:54 WARN]: [TabList] Plugin TabList v5.5.4 generated an exception while executing task 220006
java.lang.NoSuchMethodError: org.bukkit.entity.Player.displayName()Lnet/kyori/adventure/text/Component;
at hu.montlikadani.tablist.bukkit.utils.stuff.Complement2.getDisplayName(Complement2.java:29) ~[?:?]
at hu.montlikadani.tablist.bukkit.utils.Variables.setPlaceholders(Variables.java:206) ~[?:?]
at hu.montlikadani.tablist.bukkit.utils.Variables.replaceVariables(Variables.java:117) ~[?:?]
at hu.montlikadani.tablist.bukkit.tablist.TabHandler.sendTab(TabHandler.java:219) ~[?:?]
at hu.montlikadani.tablist.bukkit.tablist.TabManager.lambda$addPlayer$0(TabManager.java:61) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-443]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-443]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-443]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by TheNety** [comment]
Hi, this dev build should fix the issue. Download from here under Artifacts https://github.com/montlikadani/TabList/actions

**Comment by toby-ger** [comment]
which of them should I download please?

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: TheNety ***@***.***>
Gesendet: Saturday, June 12, 2021 1:31:22 AM
An: montlikadani/TabList ***@***.***>
Cc: Tobi ***@***.***>; Author ***@***.***>
Betreff: Re: [montlikadani/TabList] The tablist is completely gone (#244)


Hi, this dev build should fix the issue. Download from here under Artifacts https://github.com/montlikadani/TabList/actions

**Comment by TheNety** [comment]
The newest one. Just click the link I sent and then download by clicking here.
![image](https://user-images.githubusercontent.com/42073765/121774041-53f8d180-cb80-11eb-8626-9ce7bd427787.png)
Please let us know if it fixes your issue!

**Comment by toby-ger** [comment]
Thank you you best

**Comment by toby-ger** [comment]
always when the plugin is on it doesn't work? 
[CommandBlocker.zip](https://github.com/montlikadani/TabList/files/6642129/CommandBlocker.zip)

**Comment by montlikadani** [comment]
It is not caused by our plugin.

**Comment by toby-ger** [comment]
ok thanks then i have to turn to the other plugin, thank you very much
