### ISSUE TITLE
nullified plugin

### ISSUE THREAD

**Issue by drfleetles** [montlikadani/TabList#249]
### Problem
all commands i try to do in the game return null on the console and produce a bunch of errors
i just downloaded the plugin and it starts producing errors straight away. I am on 1.17 by the way

the console error is one example. all the commands produce output like that

### Details
Plugin version: v5.5.4

Software version: Spigot

Relevant plugins: 

### Console error
```
`28.06 21:17:15 [Server] Server thread/INFO Dr_Fleetles issued server command: /tl toggle all
28.06 21:17:15 [Server] Server thread/ERROR null
28.06 21:17:15 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tl' in plugin TabList v5.5.4
28.06 21:17:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
28.06 21:17:15 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class hu.montlikadani.tablist.bukkit.tablist.TabTitle
28.06 21:17:15 [Server] INFO at hu.montlikadani.tablist.bukkit.commands.list.toggle.toggleTab(toggle.java:73) ~[?:?]
28.06 21:17:15 [Server] INFO at hu.montlikadani.tablist.bukkit.commands.list.toggle.run(toggle.java:51) ~[?:?]
28.06 21:17:15 [Server] INFO at hu.montlikadani.tablist.bukkit.commands.Commands.onCommand(Commands.java:110) ~[?:?]
28.06 21:17:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot_1.17.jar:3162-Spigot-f773da8-b121d3b]
28.06 21:17:15 [Server] INFO ... 19 more`
```

### Configuration file(s)

tablist.yml https://hastebin.com/iriwujewes.yaml
groups: https://hastebin.com/ayusehaven.properties
messages: https://hastebin.com/fixeroroja.less
animcreator: https://hastebin.com/aviyixefes.less
config: https://hastebin.com/usutaheyip.yaml

**Comment by montlikadani** [comment]
Use the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page.

**Comment by drfleetles** [comment]
did you just upload it?. i will test it out

**Comment by drfleetles** [comment]
ok I do not get internal errors anymore. but i dont see the tablist modified. I will check the tablist config

**Comment by drfleetles** [comment]
the tablist config looks fine but there is this added file called toggled tablist

**Comment by montlikadani** [comment]
...and what is the problem with it? Also try to not spam this issue with unnecessary information.

**Comment by drfleetles** [comment]
The problem now is I cant see the tablist. it is normal, i only see my name

**Comment by montlikadani** [comment]
You toggled the visibility of your tablist with `/tl toggle`. Perform this command again.

**Comment by drfleetles** [comment]
ok. I thought I did that, but it worked! i feel dumb :(
