### ISSUE TITLE
Fix an unknown tablist bug

### ISSUE THREAD

**Issue by montlikadani** [montlikadani/TabList#25]
Error:
`[17:39:53 WARN]: [TabList] Plugin TabList v2.4.6 generated an exception while executing task 120
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_161]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_161]
	at hu.montlikadani.TabList.TabList$8.run(TabList.java:621) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-c5afb9f-21d5f75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]`

**Comment by montlikadani** [comment]
For now, an empty exception catch can be solved.
