### ISSUE TITLE
how do i put a hashtag in the tablist, through tablist.yml

### ISSUE THREAD

**Issue by fuckcuff** [montlikadani/TabList#280]
### Type of bug

Other

### TabList version

 [TabList] > Enabled v5.5.5! (48ms)

title says it all

### Software version

[23:27:29 INFO]: Checking version, please wait... [23:27:29 INFO]: This server is running Paper version git-Paper-259 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 810d200)

### TabList configuration files

s

### Bug description

s

**Comment by montlikadani** [comment]
`#`

**Comment by fuckcuff** [comment]
putting a # alone removes everything after it

**Comment by montlikadani** [comment]
Show screenshot

**Comment by montlikadani** [comment]
Please update to 5.5.6 version of TabList

**Comment by fuckcuff** [comment]
alright thanks

**Comment by montlikadani** [comment]
If your issue is solved, please close this issue.

**Comment by fuckcuff** [comment]
nope still not fixed
this is my tablist.yml
```header:
- "&l&o&7BALLS"
- ""
- "&6demented#5745"```
my console just gets spammed with a bunch of warnings like this:
```[16:27:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:27:59 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 32
[16:27:59 WARN]:        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
[16:27:59 WARN]:        at java.base/java.lang.String.charAt(String.java:1512)
[16:27:59 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.utils.reflection.JsonComponent.parseProperty(JsonComponent.java:119)
[16:27:59 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:51)
[16:27:59 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.tablist.TabTitle.sendTabTitle(TabTitle.java:61)
[16:27:59 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.tablist.TabHandler.sendTab(TabHandler.java:253)
[16:27:59 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.tablist.TabManager.lambda$addPlayer$0(TabManager.java:58)
[16:27:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:27:59 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:27:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:27:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:27:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:27:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:28:00 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: 32
[16:28:00 WARN]:        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
[16:28:00 WARN]:        at java.base/java.lang.String.charAt(String.java:1512)
[16:28:00 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.utils.reflection.JsonComponent.parseProperty(JsonComponent.java:119)
[16:28:00 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:51)
[16:28:00 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.tablist.TabTitle.sendTabTitle(TabTitle.java:61)
[16:28:00 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.tablist.TabHandler.sendTab(TabHandler.java:253)
[16:28:00 WARN]:        at TabList-5.5.6.jar//hu.montlikadani.tablist.bukkit.tablist.TabManager.lambda$addPlayer$0(TabManager.java:58)
[16:28:00 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:28:00 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:28:00 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:28:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:28:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:28:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)```

but when i remove the # its fine

**Comment by fuckcuff** [comment]
ALSO, as you can see in my tablist.yml im trying to use bold AND italic text but only one works, depending on which one is last. so if i have &7&o&l i get gray, bold text but the &o is supposed to make it italic aswell

**Comment by montlikadani** [comment]
Try the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts. You can install the jar from this ZIP package.

**Comment by fuckcuff** [comment]
both issues are fixed in that jar, thanks :)

**Comment by fuckcuff** [comment]
one more thing tho, is there an option to remove the "*" before the %tps% when its at 20.0? i cant find it

**Comment by montlikadani** [comment]
No, you can't, `*` shows that the tps is more than 20.0 like in Paper's `tps` command. But if you want to show the overflowed amount of tps use `%tps-overflow%`

**Comment by fuckcuff** [comment]
yeah that fixes it, thank you!
