### ISSUE TITLE
Scoreboard objective of PingTab is already exists

### ISSUE THREAD

**Issue by Aadi-mone** [montlikadani/TabList#289]
### Type of bug

Error in console

### TabList version

the latest version u just launched today

### Software version

PapperMC 1.16.5

### Relevant plugins

just that plugin

### TabList configuration files

i didn't change anything installed and started the server and got the error

### Bug description

```yml
[19:03:19 WARN]: [TabList] Plugin TabList v5.5.7 generated an exception while executing task 3328
java.lang.IllegalArgumentException: An objective of name 'PingTab' already exists
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:47) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:84) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:62) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:30) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:20) ~[patched_1.16.5.jar:git-Paper-786]
        at hu.montlikadani.tablist.bukkit.Objects.lambda$startTask$2(Objects.java:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-786]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-786]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[19:03:19 WARN]: [TabList] Plugin TabList v5.5.7 generated an exception while executing task 3329
java.lang.IllegalArgumentException: An objective of name 'PingTab' already exists
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:47) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:84) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:62) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:30) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:20) ~[patched_1.16.5.jar:git-Paper-786]
        at hu.montlikadani.tablist.bukkit.Objects.lambda$startTask$2(Objects.java:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-786]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-786]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[19:03:19 WARN]: [TabList] Plugin TabList v5.5.7 generated an exception while executing task 3330
java.lang.IllegalArgumentException: An objective of name 'PingTab' already exists
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:47) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:84) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:62) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:30) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:20) ~[patched_1.16.5.jar:git-Paper-786]
        at hu.montlikadani.tablist.bukkit.Objects.lambda$startTask$2(Objects.java:82) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-786]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-786]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-786]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by montlikadani** [comment]
Disable tablist objectives option temporarily in config file.

**Comment by Aadi-mone** [comment]
can you say which part? or thing itself.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/blob/90cf12331237c16b63d05cd2525cdd74c19ef982/bukkit/src/main/resources/config.yml#L168-L169

**Comment by Aadi-mone** [comment]
**thank you for helping and adding the version to spigot.**

**Comment by montlikadani** [comment]
Keep this issue opened, this exception still was not fixed for others. We need to investigate this, but without reproduction I can't do too much thing. I also don't understand how this exception thrown.

**Comment by Aadi-mone** [comment]
**okay, but is there anything in which I can help?
or I leave this thread, and you'll take care?**

**Comment by montlikadani** [comment]
If you're a developer, you can open a PR at any time, if you have any fix for the current TL code.

Anyway, the exception is refers to this line:
https://github.com/montlikadani/TabList/blob/90cf12331237c16b63d05cd2525cdd74c19ef982/bukkit/src/main/java/hu/montlikadani/tablist/bukkit/Objects.java#L80-L83
As it can be seen that the scoreboard objective registration is called once if the objective is not exists, if exist it will not registers a new one with the corresponding name. But the player's scoreboard somehow returns that the objective is not registered, so it returns `null`.

**Comment by Aadi-mone** [comment]
**I'm not a java developer 😅 
and as a normal human, this plugin has a scoreboard also? if yes I think it's not needed. 
and if you know the problem is on the code it self then you can remove that part?
and sorry if I am wrong as I don't know java.
thanking you
Adarsh.**

**Comment by montlikadani** [comment]
The above attached commit will "hopefully" fixes this issue. You will be able to test in the next release.

**Comment by Aadi-mone** [comment]
nice, what about #291

**Comment by montlikadani** [comment]
It is not related to this issue

**Comment by Aadi-mone** [comment]
ok i'll talk there
