### ISSUE TITLE
Plugin breaks when I log out and back in

### ISSUE THREAD

**Issue by bsickinger** [montlikadani/TabList#29]
If I do a server restart, the tab list shows up correctly. The second I log out and log back into the server it is broken for me and anyone else online.

**Comment by bsickinger** [comment]
Group names still display but header and footers do not

**Comment by bsickinger** [comment]
So. more info. This is getting reset for players when they log out and log back in.  Players still online are not affected.  The only way to fix the problem for players who log back in is a /tl toggle off and /tl toggle on

**Comment by montlikadani** [comment]
What mistakes does the console write?

**Comment by bsickinger** [comment]
Logs are spammed with two warnings:

[14:37:44] [Craft Scheduler Thread - 158/WARN]: [TabList] Plugin TabList v2.4.8 generated an exception while executing task 357
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_141]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_141]
	at hu.montlikadani.TabList.TabList$9.run(TabList.java:648) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-2086bb0-1988d7f]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigotmc-1.12.2-R0.1.jar:git-Spigot-2086bb0-1988d7f]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[14:37:44] [Craft Scheduler Thread - 131/WARN]: [TabList] Plugin TabList v2.4.8 generated an exception while executing task 342
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_141]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_141]
	at hu.montlikadani.TabList.TabList$9.run(TabList.java:648) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-2086bb0-1988d7f]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigotmc-1.12.2-R0.1.jar:git-Spigot-2086bb0-1988d7f]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]


Only config change I made was to the header/footer and those look like this:

tablist:
  # Enable the tab? (Header, footer)
  enable: true
  # What world does not display the tab?
  # If you do not want to disable any of the worlds, then write it as follows: disabled-worlds: []
  disabled-worlds:
  - lobby
  - hub
  # Tab update time interval. (In ticks!)
  # Set 0 to disable the tab refresh.
  interval: 4
  header:
    - '&3Haven&6Craft &cTowny\n&7 &6Ping:&a %ping%&7ms\n&5&m======================'

  footer:
    - '&5&m======================&7\n&e&l Players:&6 %online-players%&7/&6%max-players%\n\n&7<28>&f&o Website&7:&2 &nhttps://HavenCraftServ.enjin.com&7 <28>\n<28>&f&o Discord&7:&2 &nDiscord.gg/MbjSpua&7 <28>'

  # Per world tablist.
  # Unlimited world.

**Comment by montlikadani** [comment]
This duplicate of #25 
### Thank you for reporting it!
