### ISSUE TITLE
Message spam in proxy chat

### ISSUE THREAD

**Issue by olikols07** [montlikadani/TabList#296]
### Type of bug

Error in console

### TabList version

TabList version 5.5.9 An ultimate animated tablist Author: montlikadani

### Software version

This server is running Paper version git-Paper-391 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3e73355 on ver/1.17.1) You are running the latest version Previous version: git-Paper-22 (MC: 1.18)

### Relevant plugins

Plugins (9): dynmap, Essentials, EssentialsChat, LuckPerms, OpenInv, SuperVanish, TabList, Vault, WorldEdit

### Console error (if applicable)

[13:08:08 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@3eba57a7, id=40, owner=hu.montlikadani.tablist.TabList@3e05586b, task=hu.montlikadani.tablist.tablist.TabManager$$Lambda$903/0x0000000801014840@6b2e89d3, delay=10, period=180, running=true) encountered an exception
java.lang.NoClassDefFoundError: hu/montlikadani/tablist/Global
        at hu.montlikadani.tablist.tablist.text.LegacyTextConverter.toBaseComponent(LegacyTextConverter.java:39) ~[?:?]
        at hu.montlikadani.tablist.tablist.PlayerTab.getNextHeader(PlayerTab.java:66) ~[?:?]
        at hu.montlikadani.tablist.tablist.PlayerTab.update(PlayerTab.java:220) ~[?:?]
        at hu.montlikadani.tablist.tablist.TabManager.lambda$start$2(TabManager.java:84) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: hu.montlikadani.tablist.Global
        ... 8 more

### TabList configuration files

https://paste.gg/p/anonymous/da294b27ee1041bab399c7338980d985

### Bug description

Does not seam to do anything wierd other than display this message in console on start up once and when a player joins it start repeating over and over again.
hope you have a nice day, sincerely olikol 👍

**Comment by TheNety** [comment]
That does indeed happen on latest Waterfall. This is the startup error:
![image](https://user-images.githubusercontent.com/42073765/144630161-85f9403c-b9eb-4629-aa0f-673733fd25aa.png)

Possibly because of [this](https://github.com/montlikadani/TabList/blob/master/bungee/src/main/java/hu/montlikadani/tablist/config/ConfigConstants.java#L121) (and [this](https://github.com/montlikadani/TabList/blob/master/bungee/src/main/java/hu/montlikadani/tablist/tablist/text/LegacyTextConverter.java#L8) and [this](https://github.com/montlikadani/TabList/blob/master/bungee/src/main/java/hu/montlikadani/tablist/tablist/text/LegacyTextConverter.java#L206))

**Comment by montlikadani** [comment]
Somehow the Global project is not included to the bungee built jar file, so that is why it throws this excetion.

**Comment by Kicke87** [comment]
i have that same problem,  how do i install the newest build? 
Dont have the server on my computer, i have shockbyte as host.

**Comment by TheNety** [comment]
Download the newest build (at the top) from [here](https://github.com/montlikadani/TabList/actions) and upload the jar via FTP in your plugins folder
