### ISSUE TITLE
Console Repeat Messages Bug

### ISSUE THREAD

**Issue by SirSamurai** [montlikadani/TabList#298]
### Type of bug

Error in console

### TabList version

TabList version 5.5.9 [11:10:54 INFO]: An ultimate animated tablist [11:10:54 INFO]: Author: montlikadani

### Software version

This server is running Mohist version 1.12.2-248 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)

### Relevant plugins

Plugins (13): Citizens, DeluxeJoin, FastAsyncWorldEdit, HolographicDisplays, LuckPerms, PlaceholderAPI, ProtocolLib, SkinsRestorer, TabList, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Console error (if applicable)
```
java.lang.NullPointerException
[11:09:21 WARN]:        at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.unregisterTeam(ReflectionHandled.java:175)
[11:09:21 WARN]:        at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:42)
[11:09:21 WARN]:        at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:160)
[11:09:21 WARN]:        at hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:186)
[11:09:21 WARN]:        at hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:323)
[11:09:21 WARN]:        at hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:290)
[11:09:21 WARN]:        at hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$0(Groups.java:275)
[11:09:21 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[11:09:21 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50)
[11:09:21 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:09:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:09:21 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:09:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
( And repeating until i leave )

### TabList configuration files

[config.yml.txt](https://github.com/montlikadani/TabList/files/7654331/config.yml.txt)

### Bug description

When i enter to the server, or someone joins, they start sending messages from the console, and it doesn't stop until I get out, I think it has to do with groups, but the only thing I did was modify from the animations folder

( here is the anims folder -- Modified)

[anims.yml.txt](https://github.com/montlikadani/TabList/files/7654339/anims.yml.txt)

![image](https://user-images.githubusercontent.com/73261053/144718820-7388df1e-7709-42da-8242-c23a409b7037.png)
![image](https://user-images.githubusercontent.com/73261053/144718825-2a4665aa-3672-48eb-8ddf-26efdefc4390.png)

**Comment by montlikadani** [comment]
This is a known issue for Mohist. Please follow [this issue](https://github.com/montlikadani/TabList/issues/279) for further.
