### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Preparator** [montlikadani/TabList#30]
Hello, I wanter to change nickname in tablist to &5× &5&lJC &5× &dBugnutyAxiom, but it doesn't work !
Error:
>[2K [20:55:46 WARN]: [TabList] Task #1059 for TabList v2.4.8 generated an exception 
java.lang.NullPointerException: null 
at hu.montlikadani.TabList.TabList.setGroup(TabList.java:964) ~[?:?] 
at hu.montlikadani.TabList.TabList$11.run(TabList.java:945) ~[?:?] 
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-596221b-9a1fc1e] 
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-596221b-9a1fc1e] 
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-596221b-9a1fc1e] 
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e] 
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e] 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]

**Comment by montlikadani** [comment]
This error occurs when the server can not find the file. So reload the plugin to create the file.
No nickname but group prefix and suffix.

**Comment by montlikadani** [comment]
_This bug has been fixed in this version:_ https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=227536

**Comment by montlikadani** [comment]
Re-opened, this bug was re-released. [#3036429](https://www.spigotmc.org/threads/animated-tab-tablist.268246/page-17#post-3036429)

**Comment by montlikadani** [comment]
_This bug has been fixed in this version:_ https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=229856
