### ISSUE TITLE
the plugin does not work

### ISSUE THREAD

**Issue by s7an1slaw** [montlikadani/TabList#300]
### Type of bug

Other

### TabList version

TabList version 5.5.9

### Software version

git-Paper-36 (MC: 1.18)

### Relevant plugins

BetterRTP, BungeeGuard, Chunky, Coordinates, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, Matrix, Multiverse-Core, PlaceholderAPI, ProtocolLib, Quests, Scoreboard-revision*, SkinsRestorer, Skript, TabList, Vault, WorldEdit, WorldGuard

### Console error (if applicable)

[11:51:07 INFO]: [TabList] Enabling TabList v5.5.9
[11:51:07 ERROR]: Error occurred while enabling TabList v5.5.9 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
        at org.bukkit.configuration.MemorySection.get(MemorySection.java:265) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.getString(MemorySection.java:329) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at hu.montlikadani.tablist.config.constantsLoader.ConfigValues.loadValues(ConfigValues.java:192) ~[TabList-bukkit-5.5.9.jar:?]
        at hu.montlikadani.tablist.config.Configuration.loadFiles(Configuration.java:48) ~[TabList-bukkit-5.5.9.jar:?]
        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:84) ~[TabList-bukkit-5.5.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-39]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:51:07 INFO]: [TabList] Disabling TabList v5.5.9

### TabList configuration files

default configs

### Bug description

just by starting the server and the plugin does not start

**Comment by montlikadani** [comment]
Congrats for Spigot [commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/e4358b8217126bbcc3a38b0d17097ad5ab87c50a)

**Comment by wtlgo** [comment]
Same error on 

```
[14:26:59 INFO]: [TabList] Enabling TabList v5.5.9
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
[14:26:59 ERROR]: Error occurred while enabling TabList v5.5.9 (Is it up to date?)
at org.bukkit.configuration.MemorySection.get(MemorySection.java:265) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.configuration.MemorySection.getString(MemorySection.java:329) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at hu.montlikadani.tablist.config.Configuration.loadFiles(Configuration.java:48) ~[TabList-bukkit-5.5.9.jar:?]
at hu.montlikadani.tablist.config.constantsLoader.ConfigValues.loadValues(ConfigValues.java:192) ~[TabList-bukkit-5.5.9.jar:?]
at hu.montlikadani.tablist.TabList.onEnable(TabList.java:84) ~[TabList-bukkit-5.5.9.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-43]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-43]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-43]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-43]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-43]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-43]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-43]
[14:26:59 INFO]: [TabList] Disabling TabList v5.5.9
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Paper version
```
version
[14:28:48 INFO]: Checking version, please wait...
You are 1 version(s) behind
Previous version: git-Paper-36 (MC: 1.18)
[14:28:48 INFO]: This server is running Paper version git-Paper-43 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: fd4f6c5)
Download the new version at: https://papermc.io/downloads
```

**Comment by montlikadani** [comment]
Paper reverted this commit

> Congrats for Spigot [commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/e4358b8217126bbcc3a38b0d17097ad5ab87c50a) 👏

so you can install the newest build.
