### ISSUE TITLE
Warn

### ISSUE THREAD

**Issue by rkfsociety** [montlikadani/TabList#301]
### Type of bug

Error in console

### TabList version

TabList-bukkit-5.5.9

### Software version

git-Paper-42 (MC: 1.18)

### Relevant plugins

Plugins (21): AuthMe, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ez-broadcast, GetSpawners, LuckPerms, MoreMobHeads, PlaceholderAPI, Plan, PlugMan, ProtocolLib, SkinFixer, TabList, TradeSystem, UltimateAutoRestart, Vault, WorldEdit, WorldGuard

### Console error (if applicable)

[17:38:07 WARN]: Unexpected exception while parsing console command "tablist"
org.bukkit.command.CommandException: Cannot execute command 'tablist' in plugin TabList v5.5.9 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-42]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:839) ~[paper-1.18.jar:git-Paper-42]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:507) ~[paper-1.18.jar:git-Paper-42]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:481) ~[paper-1.18.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-42]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>

### TabList configuration files

https://paste.gg/p/anonymous/cd1a5eb276824ee79d2ce2ce80e3f7b1

### Bug description

it just doesn't work

**Comment by montlikadani** [comment]
Show the full log from start to end and send to pastebin.com

**Comment by rkfsociety** [comment]
this happened after updating the paper core, can I write to them? before that, the plugin worked fine.

**Comment by montlikadani** [comment]
No, update your Paper again to the newest build.

**Comment by rkfsociety** [comment]
https://pastebin.com/pSyUEUsD

**Comment by rkfsociety** [comment]
I just don't have time to update, okay. thanks.
