### ISSUE TITLE
Nametags in game stopped appearing after installing the plugin.

### ISSUE THREAD

**Issue by HDProduction010** [montlikadani/TabList#308]
### Type of bug

Other

### TabList version

5.6.0

### Software version

1.16.5 Purpur

### TabList configuration files

Config

https://paste.gg/p/anonymous/25a861fcc4ee4184bff35568b53f36d5

Tablist
https://paste.gg/p/anonymous/8f1862b01b7c491faed338c2d096464e

### Bug description

All nametags are gone from the server and no other plugins seem to be effecting it other than this one.

**Comment by HDProduction010** [comment]
Seems the issue is the plugin overwrites NTE (NameTagEdit) Which allows for color config in the plugin itself.

Any ideas on how to fix this?

**Comment by montlikadani** [comment]
A similar problem was reported at some point, but it has since been fixed, so name tags should appear. Unless that name tag editor plugin does not modify name tags with scoreboard teams.
> 5.6.0

Please perform `/version` in your console and paste the full output here.

**Comment by HDProduction010** [comment]
[01:09:27 INFO]: TabList version 5.5.7
[01:09:27 INFO]: An ultimate animated tablist.
[01:09:27 INFO]: Author: montlikadani

**Comment by montlikadani** [comment]
You're using 5.5.7 version of tablist, consider updating to 5.6.0, and make sure the issue still exists.

**Comment by HDProduction010** [comment]
I have updated to 5.6.0 and it is still doing the same thing.

I have also turned off the animations as it decreased server performance when we got more than 20 people on the server.

Keeping in mind that we have 1800+ member who have joined our server performance is quite important. Is there any way to increase the performance of the tablist and run the animations at the same time?

**Comment by montlikadani** [comment]
Animations well optimized and these are running in asynchronous thread. To check for performance use Spark and timings.

**Comment by Katrix** [comment]
Problem for us as well

```
[Sat, 25. Dec 2021 18:29:46 UTC INFO] TabList version 5.6.0
[Sat, 25. Dec 2021 18:29:46 UTC INFO] An ultimate animated tablist
[Sat, 25. Dec 2021 18:29:46 UTC INFO] Author: montlikadani
```

A temporary fix I did was to set `change-prefix-suffix-in-tablist.enabled = false`

**Comment by HDProduction010** [comment]
Changing this will not allow Prefixes in the tab which is needed as some of our users use that for distinguishment of other users.

To add onto the authors comment. I deleted the animations right from the animations tab. This stopped all animations however when it is on a timings report states that 7TPS is dropped when we try to enable it.

**Comment by montlikadani** [comment]
I will look to this name tag issue.

As I mentioned before show timings and spark report. Just stating "the animations causing lags" is not a prove. _For me I can't reproduce with 1000 players._

**Comment by montlikadani** [comment]
Also show all your plugins on your server.

**Comment by Katrix** [comment]
```
[12:52:56 INFO]: Plugins (50): AsyncWorldEdit, BanManager, ChatFeelings, Chatty, CommandHook, CoreProtect, CraftBook, DiscordSRV, dynmap, Essentials, FarmControl, FeelingsRelay*, FirstJoinPlus*, GriefDefender, HeadDatabase, HomeSweetHome*, InventoryRollback, KatLib*, KillCount*, KillY1000*, LagMeter*, LibsDisguises, LuckPerms, LWC, MagicalWarps*, MessageAnnouncer, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MyCommand, OnTime*, OpenInv, Paintball, PerWorldInventory, PlugMan, PrometheusExporter, ProtocolLib, RemiSux, Rider*, ScuffedHacks*, ServerListPlus, spark, SuperVanish, TabList, Vault, ViaBackwards, ViaVersion, VoxelSniper, WorldBorder, WorldEdit
```

Some are custom plugins, but I doubt they are the cause.

**Comment by montlikadani** [comment]
There is an objective created on your server that includes the hide option on the players scoreboard so the name tag will not appear. You can list these objectives using the `scoreboard players list` or `scoreboard objectives list` command. But it is enough if you send me the output of these commands.

**Comment by Katrix** [comment]
```
[Sun, 26. Dec 2021 15:08:50 UTC INFO] There are 2 objectives: [pf_skip], [ms]
[Sun, 26. Dec 2021 15:08:45 UTC INFO] There are 1 tracked entities: Kogasa_Tatara
```

**Comment by montlikadani** [comment]
Maybe the `pf_skip` objective contain this hide option. Did you tried to change or remove this objective? `/scoreboard objectives remove pf_skip`

**Comment by HDProduction010** [comment]
I saw that you said you would  look into the name tag issue. Is there any information you need from me to make this work?

**Comment by HDProduction010** [comment]
So I have determined that this issue is stemming from another plugin... I will try to investigate this more and I will let you know what I find.

**Comment by HDProduction010** [comment]
[23:39:03 WARN]: [TabList] Plugin TabList v5.6.0 generated an exception while executing task 827
java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1225) ~[?:?]
        at net.minecraft.server.v1_16_R3.Scoreboard.getPlayerScoreForObjective(SourceFile:82) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftScore.setScore(CraftScore.java:59) ~[patched_1.16.5.jar:git-Purpur-1171]
        at hu.montlikadani.tablist.Objects.lambda$startTask$1(Objects.java:133) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        
        
        This is also another error I have been getting randomly through out the servers running state.

**Comment by montlikadani** [comment]
Try to install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.

**Comment by montlikadani** [comment]
> I saw that you said you would look into the name tag issue. Is there any information you need from me to make this work?



> There is an objective created on your server that includes the hide option on the players scoreboard so the name tag will not appear. You can list these objectives using the `scoreboard players list` or `scoreboard objectives list` command. But it is enough if you send me the output of these commands.

^

**Comment by HDProduction010** [comment]
The only thing that pops up is PingTab, ms

**Comment by montlikadani** [comment]
Now try to install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.

**Comment by HDProduction010** [comment]
Sorry I was out for the holidays. After adding the plugin we were able to get nametags back but the nametags are no longer colored to their predefined colors in our LP DB.

We want to try to have colors in the same servers and we want to make them work together. This is a step in the right direction though so thank you!
