### ISSUE TITLE
java.util.UnknownFormatConversionException: Conversion = '%'

### ISSUE THREAD

**Issue by Graspberries** [montlikadani/TabList#309]
### Type of bug

Other

### TabList version

TabList version 5.6.0

### Software version

This server is running Paper version git-Paper-398 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 244b392 on ver/1.17.1) You are 4 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-792 (MC: 1.16.5)

### Relevant plugins

BetterTeams (version 4.2.1)
PlaceholderAPI (version 2.11.0)

### Console error (if applicable)

[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: java.util.UnknownFormatConversionException: Conversion = '%'
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.util.Formatter.checkText(Formatter.java:2748)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.util.Formatter.parse(Formatter.java:2734)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.util.Formatter.format(Formatter.java:2671)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.util.Formatter.format(Formatter.java:2625)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.lang.String.format(String.java:3290)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at BetterTeams.jar//com.booksaw.betterTeams.integrations.TeamPlaceholders.onPlaceholderRequest(TeamPlaceholders.java:65)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at PlaceholderAPI-2.11.0.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at PlaceholderAPI-2.11.0.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at PlaceholderAPI-2.11.0.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at PlaceholderAPI-2.11.0.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.utils.variables.Variables.setPlayerPlaceholders(Variables.java:260)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.utils.variables.Variables.replaceVariables(Variables.java:199)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.GroupPlayer.getSuffix(GroupPlayer.java:294)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.GroupPlayer.getTabNameWithPrefixSuffix(GroupPlayer.java:315)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:212)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:161)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:186)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:323)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:290)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at TabList-bukkit-5.6.0.jar//hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$0(Groups.java:275)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[19:09:57] [Craft Scheduler Thread - 387 - TabList/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

### TabList configuration files

https://paste.gg/p/anonymous/ffd4abd5fd804c3a934f3734ad43d441

### Bug description

I actually dont know how this happened, the plugin works perfectly but doesnt shows the **[Owner] Playername** and the team they are in. Its likely the placeholder, but I dont know if the problem is in BetterTeams or this plugin. This doesnt affects the tps, tps is stable.

**Comment by montlikadani** [comment]
It is caused by BetterTeams plugin
