### ISSUE TITLE
Player's groups aren't showing + error in console

### ISSUE THREAD

**Issue by bouchbi** [montlikadani/TabList#311]
### Type of bug

Error in console

### TabList version

Tablist-bungee-v2.2.6

### Software version

Lightfall (waterfall fork)

### Relevant plugins

BungeeHub, SkinsRestorer, TabList

### Console error (if applicable)

[17:45:20 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@273c947f, id=5, owner=hu.montlikadani.tablist.TabList@37c5fc56, task=hu.montlikadani.tablist.tablist.TabManager$$Lambda$404/44033632@2cbb21a2, delay=10, period=500, running=true) encountered an exception
java.lang.NullPointerException: null
at hu.montlikadani.tablist.tablist.PlayerTab.getNextHeader(PlayerTab.java:46) ~[?:?]
at hu.montlikadani.tablist.tablist.PlayerTab.update(PlayerTab.java:220) ~[?:?]
at hu.montlikadani.tablist.tablist.TabManager.lambda$start$2(TabManager.java:84) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[lightfall.jar:git:lightfall-Bootstrap:1.17-R0.1-SNAPSHOT:76adce7:1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

### TabList configuration files

https://paste.gg/p/anonymous/07d40a8a2c1648fda559de0e97c1dc50

### Bug description

I don't really see an issue, however the player groups aren't deisplaying, even with the permissions set correctly.
And I had this error in the console

**Comment by montlikadani** [comment]
You need a permission plugin for groups to work such as LuckPerms, also the error was fixed in the newest build. You can get it from [here](https://github.com/montlikadani/TabList/actions), select the first one and find artifacts.

**Comment by bouchbi** [comment]
I have a permission plugin, I have luckperms with the permissions set correctly.
Oh maybe I need it on thebungeecord as well ?

**Comment by bouchbi** [comment]
Alright, it was this, such a stupid oversight
