### ISSUE TITLE
Paper 1.18.1 - Plugin doesnt work. at all (disables)

### ISSUE THREAD

**Issue by DxtrusJonesy** [montlikadani/TabList#312]
### Type of bug

Error in console

### TabList version

Latestt (Bukkit 5.6.0)

### Software version

 This server is running Paper version git-Paper-121 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 4bf2aef)

### Relevant plugins

only placeholderapi and this plugin are on the server

`[10:25:53 INFO]: Plugins (2): PlaceholderAPI, TabList`

### Console error (if applicable)

```
[10:16:49 ERROR]: Error occurred while enabling TabList v5.6.0 (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
        at java.lang.String.charAt(String.java:1512) ~[?:?]
        at hu.montlikadani.tablist.config.CommentedConfig.insertComments(CommentedConfig.java:81) ~[TabList-bukkit-5.6.0.jar:?]
        at hu.montlikadani.tablist.config.CommentedConfig.save(CommentedConfig.java:62) ~[TabList-bukkit-5.6.0.jar:?]
        at hu.montlikadani.tablist.config.CommentedConfig.save(CommentedConfig.java:41) ~[TabList-bukkit-5.6.0.jar:?]
        at hu.montlikadani.tablist.config.constantsLoader.ConfigValues.loadValues(ConfigValues.java:261) ~[TabList-bukkit-5.6.0.jar:?]
        at hu.montlikadani.tablist.config.Configuration.loadFiles(Configuration.java:48) ~[TabList-bukkit-5.6.0.jar:?]
        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:86) ~[TabList-bukkit-5.6.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-121]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-121]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-121]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-121]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-121]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-121]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:16:49 INFO]: [TabList] Disabling TabList v5.6.0
```

### TabList configuration files

All are default, generated by the plugin.
The main config is emptied.

### Bug description

The plugin refuses to load on Paper 1.18.1, and im not the only one with this issue.

This is a freshly created server with all default configs from both PlaceHolderAPI and this plugin.
After loading, the main config file is emptied (its completely blank) and the plugin does not stay enabled.

**Comment by DxtrusJonesy** [comment]
works on 1 version behind (Paper 1.18 120)

**Comment by montlikadani** [comment]
Install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts. This issue already been fixed in this build.
