### ISSUE TITLE
Tablist, multiple errors.

### ISSUE THREAD

**Issue by iFrgot** [montlikadani/TabList#313]
### Type of bug

Other

### TabList version

TabList version 5.6.0 01.01 An ultimate animated tablist 01.01 Author: montlikadani

### Software version

This server is running Paper version git-Paper-"3a43821" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3a43821)

### Relevant plugins

PlaceholderAPI

### Console error (if applicable)

Error when reloading:
01.01 15:25:55 [Server] INFO iFrgot issued server command: /tablist reload
01.01 15:25:55 [Server] ERROR null
01.01 15:25:55 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tablist' in plugin TabList v5.6.0
01.01 15:25:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
01.01 15:25:55 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
01.01 15:25:55 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2285) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2096) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2077) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:55 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
01.01 15:25:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:56 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
01.01 15:25:56 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:56 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:56 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
01.01 15:25:56 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
01.01 15:25:56 [Server] INFO Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
01.01 15:25:56 [Server] INFO at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
01.01 15:25:56 [Server] INFO at java.lang.String.charAt(String.java:1509) ~[?:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.config.CommentedConfig.insertComments(CommentedConfig.java:81) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.config.CommentedConfig.save(CommentedConfig.java:62) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.config.CommentedConfig.save(CommentedConfig.java:41) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.config.constantsLoader.ConfigValues.loadValues(ConfigValues.java:261) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.config.Configuration.loadFiles(Configuration.java:48) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.TabList.reload(TabList.java:243) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.commands.list.reload.run(reload.java:19) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at hu.montlikadani.tablist.commands.Commands.onCommand(Commands.java:109) ~[TabList-bukkit-5.6.0.jar:?]
01.01 15:25:56 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
01.01 15:25:56 [Server] INFO ... 21 more

Error when starting up server
[19:30:44] [Server thread/INFO]: [TabList] Enabling TabList v5.6.0
[19:30:44] [Server thread/ERROR]: Error occurred while enabling TabList v5.6.0 (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
	at java.lang.String.charAt(String.java:1509) ~[?:?]
	at hu.montlikadani.tablist.config.CommentedConfig.insertComments(CommentedConfig.java:81) ~[TabList-bukkit-5.6.0.jar:?]
	at hu.montlikadani.tablist.config.CommentedConfig.save(CommentedConfig.java:62) ~[TabList-bukkit-5.6.0.jar:?]
	at hu.montlikadani.tablist.config.CommentedConfig.save(CommentedConfig.java:41) ~[TabList-bukkit-5.6.0.jar:?]
	at hu.montlikadani.tablist.config.constantsLoader.ConfigValues.loadValues(ConfigValues.java:261) ~[TabList-bukkit-5.6.0.jar:?]
	at hu.montlikadani.tablist.config.Configuration.loadFiles(Configuration.java:48) ~[TabList-bukkit-5.6.0.jar:?]
	at hu.montlikadani.tablist.TabList.onEnable(TabList.java:86) ~[TabList-bukkit-5.6.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"3a43821"]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[19:30:44] [Server thread/INFO]: [TabList] Disabling TabList v5.6.0

### TabList configuration files

https://paste.gg/p/anonymous/22205cde893046a28d81565c6d1e50ed

### Bug description

There are many errors, when I start up the server the plugin will sometimes fail to start, when I reload the plugin fails the first time to reload, the second time it will reload. The plugin also does not hook into placeholderapi correctly and does not display the placeholders in the tablist correctly. It just displays the placeholder name. I have tried restarting the plugin, the server and redoing the config.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/312
