### ISSUE TITLE
NullPointerException for missing constructor from PacketPlayOutScoreboardTeam class in diff platform where forge is supported

### ISSUE THREAD

**Issue by yuan746x** [montlikadani/TabList#330]
### Type of bug

Error in console

### TabList version

5.6.1

### Software version

This server is running CatServer version git-CatServer-1.12.2-a8b73e9 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)

### Relevant plugins

Plugins (10): PlugMan, LuckPerms, Vault, Essentials, PlaceholderAPI, ProtocolLib, AuthMe, dynmap, LWC, TabList

### Console error (if applicable)

[19:25:31] [Craft Scheduler Thread - 11/WARN]: java.lang.NullPointerException
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.unregisterTeam(ReflectionHandled.java:163)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:42)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:149)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:186)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:323)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:290)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$0(Groups.java:275)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at java.lang.Thread.run(Thread.java:853)
[19:25:31] [Craft Scheduler Thread - 11/WARN]: java.lang.NullPointerException
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:66)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:149)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:186)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:323)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:290)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$0(Groups.java:275)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:25:31] [Craft Scheduler Thread - 11/WARN]:  at java.lang.Thread.run(Thread.java:853)

[19:25:31] [Server thread/WARN]: java.lang.NullPointerException
[19:25:31] [Server thread/WARN]:        at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.unregisterTeam(ReflectionHandled.java:163)
[19:25:31] [Server thread/WARN]:        at hu.montlikadani.tablist.tablist.groups.Groups.removePlayerGroup(Groups.java:229)
[19:25:31] [Server thread/WARN]:        at hu.montlikadani.tablist.TabList.onPlayerQuit(TabList.java:389)
[19:25:31] [Server thread/WARN]:        at hu.montlikadani.tablist.listeners.Listeners.onPlayerLeave(Listeners.java:55)
[19:25:31] [Server thread/WARN]:        at catserver.server.executor.asm.generated.GeneratedEventExecutor141.execute(Unknown Source)
[19:25:31] [Server thread/WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67)
[19:25:31] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:25:31] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503)
[19:25:31] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488)
[19:25:31] [Server thread/WARN]:        at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:524)
[19:25:31] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1309)
[19:25:31] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:366)
[19:25:31] [Server thread/WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:223)
[19:25:31] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:992)
[19:25:31] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474)
[19:25:31] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826)
[19:25:31] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685)
[19:25:31] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:853)

### TabList configuration files

Default profile

### Bug description

console Repeated warnings

**Comment by montlikadani** [comment]
Please link me the CatServer software source, as it seems like this software doing a bad thing as like Mohist.

**Comment by yuan746x** [comment]
> 请将 CatServer 软件源链接给我，因为看起来这个软件像墨家一样在做坏事。在那之前，我无法做任何事情来修复它。

https://github.com/Luohuayu/CatServer

**Comment by montlikadani** [comment]
As I thought, this software is also removing or making it unvisible the constructor that TL needs it. Now, I am ask a question: How do I fix this? Plus, I see 0.5 activity on CatServer issues, so sometimes the author answers to an issue that was created 1-2 months ago.

**Comment by montlikadani** [comment]
So I suggest to you: Switch to Mohist server, or report an issue to CatServer with title `missing/unvisible constructor in PacketPlayOutScoreboardTeam class`

**Comment by yuan746x** [comment]
> 所以我建议你：切换到Mohist服务器，或者用title`missing/unvisible constructor in PacketPlayOutScoreboardTeam class` 或idk向CatServer报告问题

ok

**Comment by montlikadani** [comment]
Closing this issue now. I can not do anything in my side to fix this issue. The only way to remove that NullPointerException is to make a fail-fast or just a notnull condition and warn the user about this, but it makes no sense to do this.
