### ISSUE TITLE
console spam eror

### ISSUE THREAD

**Issue by ahmed3ro** [montlikadani/TabList#35]
```
11:43:02 WARN]: java.lang.NoSuchFieldException: recentTps
[11:43:02 WARN]: 	at java.lang.Class.getField(Class.java:1703)
[11:43:02 WARN]: 	at hu.montlikadani.TabList.TabList.getTPS(TabList.java:776)
[11:43:02 WARN]: 	at hu.montlikadani.TabList.TabList.replaceVariables(TabList.java:730)
[11:43:02 WARN]: 	at hu.montlikadani.TabList.TabList$9.run(TabList.java:667)
[11:43:02 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[11:43:02 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:43:02 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:43:02 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:43:02 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:43:02 WARN]: [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues
```

i use last verison of tap list and minecraft 1.12.2

**Comment by montlikadani** [comment]
Do you use CraftBukkit or Spigot?

**Comment by MaxCF1221** [comment]
CrafyBukkit.

**Comment by MaxCF1221** [comment]
CraftBukkit.

**Comment by montlikadani** [comment]
This error has already occurred and is duplicated.

**Comment by MaxCF1221** [comment]
So, what's the solution ?

**Comment by montlikadani** [comment]
For now nothing is being fixing.
Just do this to avoid using the %tps% placeholder.
