### ISSUE TITLE
[20:50:59 WARN]: java.lang.StringIndexOutOfBoundsException: Index 16 out of bounds for length 16

### ISSUE THREAD

**Issue by candy999** [montlikadani/TabList#365]
### Type of bug

Error in console

### TabList version

TabList version 5.6.4 

### Software version

Previous: git-Purpur-1802 (MC: 1.19.2)

### Relevant plugins

[21:00:43 INFO]: Plugins (40): antiRedstoneClock, BlueBridgeCore, BlueBridgeWG, BlueMap, BlueMap-Essentials, Chunky, ChunkyBorder, CoreProtect, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FarmControl, FartherViewDistance, FastAsyncWorldEdit (WorldEdit), FixillegalName*, GameModeInventories, Geyser-Spigot, GSit, LockettePro, LuckPerms, MRT*, Multiverse-Core, NBTAPI, NekoMaid, OpenInv, PlaceholderAPI, PlasmoVoice, PlugManX (PlugMan), ProtocolLib, PsudoCommand, spark, Uniporter, Vault, ViaBackwards, ViaVersion, WorldGuard

### Console error (if applicable)

[20:50:59 WARN]: java.lang.StringIndexOutOfBoundsException: Index 16 out of bounds for length 16
[20:50:59 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[20:50:59 WARN]:        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[20:50:59 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[20:50:59 WARN]:        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[20:50:59 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[20:50:59 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[20:50:59 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[20:50:59 WARN]:        at java.base/java.lang.String.checkIndex(String.java:4570)
[20:50:59 WARN]:        at java.base/java.lang.StringUTF16.checkIndex(StringUTF16.java:1616)
[20:50:59 WARN]:        at java.base/java.lang.StringUTF16.charAt(StringUTF16.java:1421)
[20:50:59 WARN]:        at java.base/java.lang.String.charAt(String.java:1529)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.JsonComponent.parseProperty(JsonComponent.java:94)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:159)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:78)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:213)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:161)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:187)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:351)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:304)
[20:50:59 WARN]:        at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$1(Groups.java:288)
[20:50:59 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:50:59 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:50:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:50:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:50:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:50:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)

### TabList configuration files

hook:

  # Hook to PlaceholderAPI to use custom placeholders.
  placeholderapi: true

# Fake players that can be added to the player list.
fake-players:
  enabled: false

  # Do we count the added fake players to the %online-players% placeholder?
  count-fake-players-to-online-players: false

# If enabled, the gray color will not appear to other players when the player's game mode is spectator.
# The gray color will only show for the spectator player.
# Requires ProtocolLib!
remove-gray-color-from-tab-in-spectator: false

# true - does not count vanished players in %online-players% placeholder.
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
ignore-vanished-players-in-online-players: false

# true - count vanished staff in %staff-online% placeholder,
# but they need to have "tablist.onlinestaff" permission set.
# false - does not count vanished staff in the %staff-online% placeholder
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
count-vanished-staffs: true

# Hide player from player list when a player is AFK?
# Requires Essentials or CMI plugin!
hide-player-from-tab-when-afk: false

# Hide all players from the player list?
# This removes all players from the player list, but the player that has the
# group set is retained as it is not changed during removal, so your group
# will be restored if this option is disabled.
# Requires ProtocolLib to fix view distance issue! (https://github.com/montlikadani/TabList/issues/147)
hide-players-from-tablist: false

# Different player list in different world.
per-world-player-list:
  enabled: false

  # You can specify worlds, which will share the same list of players
  world-groups:

    # The key name, can be anything
    example1:
    - exampleWorld
    - exampleAnotherWorld
    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2

# Placeholders formatting
placeholder-format:

  # When the player changes the AFK status, change his tablist name format?
  afk-status:
    enable: true

    # Should the AFK format display in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    # Show player's group if the player is AFK?
    show-player-group: true

    # Format when the player is AFK.
    format-yes: ' &7[離]&r'

    # Format when the player is not AFK.
    format-no: ''

    # Sort AFK players to the bottom of the player list?
    sort-last: false
  time:

    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: GMT8

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Format of %server-time% placeholder.
    time-format: mm:HH

    # Format of %date% placeholder.
    date-format: dd/MM/yyyy

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%ping% <= 200'
    - '&6%ping% >= 200'
    - '&c%ping% > 500'

  # TPS color format for %tps% placeholder.
  tps:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 19.14
    size: 2

  # Memory bar settings for %memory_bar% variable
  memory-bar:
    char: '|'
    size: 80
    colors:
      used: '&c'
      free: '&a'

      # When the server memory less than 80
      allocation: '&e'

      # When the server memory is on critical level (less than 40) and some resource need memory to run.
      released: '&6'

# Enable changing of prefix & suffix in player list?
change-prefix-suffix-in-tablist:
  enable: true

  # Refresh interval in server ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0, then you will need to execute the /tl reload command to refresh the groups.
  refresh-interval: 4

  # Disable groups in these worlds.
  disabled-worlds:

    # Use the list as whitelist?
    use-as-whitelist: false
    list:
    - myWorldWithUpper

  # Automatically add groups from another plugins to the tablist groups.yml on every reload?
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: true

  # Hide player's group in player list when the player is vanished?
  # Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
  hide-group-when-player-vanished: false

  # Do you want to assign global group to normal groups?
  # true - "globalGroupPrefix + normalGroupPrefix"
  # false - "normalGroupPrefix"
  assign-global-group-to-normal: false

  # Prefer player's primary Vault group when assigning tablist group from groups.yml?
  # true - player will be assigned their primary vault group where possible
  # false - applies the group that has the higher priority in the permission plugin
  prefer-primary-vault-group: true
  followNameTagVisibility: false

# Tablist objective types
# Shows your current health (with life indicator), your current ping or any NUMBER placeholder
# after the player's name (before the ping indicator).
tablist-object-type:

  # Types:
  # none - disables tablist objects
  # ping - player's ping
  # health - player's health
  # custom - custom placeholder
  type: ping

  # Interval for objects refreshing in seconds.
  refresh-interval: 4

  # In these worlds the objects will not be displayed
  disabled-worlds:
  - testingWorld

  # Objective settings
  object-settings:

    # The player's health - displayed after the player's name.
    health:

      # For these players the health will not be displayed
      restricted-players:
      - exampleplayer
      - players

    # Custom placeholder - accepts only number-ending placeholders, like %level%
    custom:
      value: '%level%'

# Check for updates?
check-update: false

# Download new releases to "releases" folder?
# This only works if the "check-update" is true.
download-updates: false

# Log plugin messages to console?
logconsole: true
tps-performance-observation-value: -1.0

### Bug description

server is work 24 day,player say lag,watch console have loop error

**Comment by montlikadani** [comment]
Install the newest build from [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) page, select the first one and find Artifacts.

**Comment by candy999** [comment]
I get is bug.
EssentialsX nick + LuckPerms
groups.yml
tabname: '%player-displayname%'

if nickname have '&' get is bug

**Comment by candy999** [comment]
`[21:45:13] [Server thread/INFO]: Decade_NepNep issued server command: /nickname &test&
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: java.lang.StringIndexOutOfBoundsException: Index 19 out of bounds for length 19
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/java.lang.String.checkIndex(String.java:4570)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/java.lang.StringUTF16.checkIndex(StringUTF16.java:1616)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/java.lang.StringUTF16.charAt(StringUTF16.java:1421)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/java.lang.String.charAt(String.java:1529)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.JsonComponent.parseProperty(JsonComponent.java:94)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:159)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:78)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:213)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:161)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:187)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:351)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:304)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$1(Groups.java:288)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:45:13] [Craft Scheduler Thread - 89 - TabList/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)

.....................................


[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: java.lang.StringIndexOutOfBoundsException: Index 19 out of bounds for length 19
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/java.lang.String.checkIndex(String.java:4570)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/java.lang.StringUTF16.checkIndex(StringUTF16.java:1616)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/java.lang.StringUTF16.charAt(StringUTF16.java:1421)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/java.lang.String.charAt(String.java:1529)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.JsonComponent.parseProperty(JsonComponent.java:94)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:159)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.utils.reflection.ReflectionUtils.getAsIChatBaseComponent(ReflectionUtils.java:78)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.updateName(ReflectionHandled.java:213)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:161)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:187)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:351)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:304)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at TabList-bukkit.jar//hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$1(Groups.java:288)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:45:31] [Craft Scheduler Thread - 99 - TabList/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[21:45:31] [Server thread/INFO]: Decade_NepNep issued server command: /nickname off
[21:45:33] [User Authenticator #12/INFO]: UUID of player OoioioO3902 is c52c4a93-baff-4ac0-98b1-38d0f8b956ae
[21:45:33] [Server thread/INFO]: OoioioO3902 joined the game
[21:45:33] [Server thread/INFO]: OoioioO3902[/180.217.78.202:58779] logged in with entity id 63768 at ([wild]1041.1349500520046, 72.0, -356.226505056897)`

**Comment by candy999** [comment]
> 
thanks ,fix it
https://github.com/montlikadani/TabList/actions/runs/3313535801
