### ISSUE TITLE
Tablist 5.6.4 incompatible with Spigot 1.19.3

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#367]
### Type of bug

Compatibility issue

### TabList version

>version TabList [08:17:40] [Server thread/INFO]: TabList version 5.6.4 [08:17:40] [Server thread/INFO]: An ultimate animated tablist [08:17:40] [Server thread/INFO]: Author: montlikadani

### Software version

>version [08:18:14] [Server thread/INFO]: This server is running CraftBukkit version 3616-Spigot-d90018e-eecb4c0 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) [08:18:14] [Server thread/INFO]: You are running the latest version

### Console error (if applicable)

```
[08:12:26] [Server thread/INFO]: [TabList] Enabling TabList v5.6.4
[08:12:26] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo
[08:12:26] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[08:12:26] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:390)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:381)
[08:12:26] [Server thread/WARN]:        at hu.montlikadani.tablist.utils.reflection.ClazzContainer.classByName(ClazzContainer.java:322)
[08:12:26] [Server thread/WARN]:        at hu.montlikadani.tablist.utils.reflection.ClazzContainer.<clinit>(ClazzContainer.java:45)
[08:12:26] [Server thread/WARN]:        at hu.montlikadani.tablist.utils.reflection.ReflectionUtils.<clinit>(ReflectionUtils.java:28)
[08:12:26] [Server thread/WARN]:        at hu.montlikadani.tablist.tablist.TabTitle.<clinit>(TabTitle.java:17)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:390)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:381)
[08:12:26] [Server thread/WARN]:        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:83)
[08:12:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:12:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:12:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:12:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539)
[08:12:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453)
[08:12:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587)
[08:12:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412)
[08:12:26] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[08:12:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
[08:12:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
[08:12:26] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### TabList configuration files

No changes to configuration or tablets since 1.19.2

### Bug description

- Build Spigot 1.19.3
- Start server
- Read logs

**Comment by montlikadani** [comment]
Made a [new release](https://www.spigotmc.org/resources/46229/update?update=481674) with 1.19.3 support
