### ISSUE TITLE
Warn while loading plugin

### ISSUE THREAD

**Issue by TymekSL** [montlikadani/TabList#368]
### Type of bug

Error in console

### TabList version

[09:59:36 INFO]: TabList version 5.6.4 [09:59:36 INFO]: An ultimate animated tablist [09:59:36 INFO]: Author: montlikadani

### Software version

You are running the latest version Previous version: git-Paper-312 (MC: 1.19.3)

### Relevant plugins

[10:00:05 INFO]: Plugins (6): eGlow, HardcoreMode*, LPC, LuckPerms, Skript,TabList

### Console error (if applicable)

[09:57:48 INFO]: [TabList] Enabling TabList v5.6.4
[09:57:48 WARN]: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo
[09:57:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177)
[09:57:48 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[09:57:48 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[09:57:48 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[09:57:48 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[09:57:48 WARN]:        at TabList-bukkit-5.6.4.jar//hu.montlikadani.tablist.utils.reflection.ClazzContainer.classByName(ClazzContainer.java:322)
[09:57:48 WARN]:        at TabList-bukkit-5.6.4.jar//hu.montlikadani.tablist.utils.reflection.ClazzContainer.<clinit>(ClazzContainer.java:45)
[09:57:48 WARN]:        at TabList-bukkit-5.6.4.jar//hu.montlikadani.tablist.utils.reflection.ReflectionUtils.<clinit>(ReflectionUtils.java:28)
[09:57:48 WARN]:        at TabList-bukkit-5.6.4.jar//hu.montlikadani.tablist.tablist.TabTitle.<clinit>(TabTitle.java:17)
[09:57:48 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[09:57:48 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[09:57:48 WARN]:        at TabList-bukkit-5.6.4.jar//hu.montlikadani.tablist.TabList.onEnable(TabList.java:83)
[09:57:48 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:57:48 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[09:57:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[09:57:48 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[09:57:48 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[09:57:48 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[09:57:48 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[09:57:48 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[09:57:48 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[09:57:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[09:57:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:57:48 INFO]: [TabList] > Enabled v5.6.4 (126ms)
[09:57:48 INFO]: [LPC] Enabling LPC v3.6.0

### TabList configuration files

no config. I didn't touch it 

### Bug description

Only warn

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/367
