### ISSUE TITLE
Console Error spam

### ISSUE THREAD

**Issue by Xeterios** [montlikadani/TabList#37]
So I've been using this plugin for a short while and I get spammed errors in the console whenever a player is online / joined the server.
```
[10:04:29 WARN]: [TabList] Plugin TabList v2.7 generated an exception while executing task 5548
java.lang.NullPointerException: null
	at hu.montlikadani.TabList.bukkit.TabList.replaceVariables(TabList.java:734) ~[?:?]
	at hu.montlikadani.TabList.bukkit.TabList$9.run(TabList.java:671) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```
I use Spigot v1.12.2-R0.1-SNAPSHOT

Please respond asap I need a fix for this quick before people get to notice the many errors that lag down the server.

**Comment by montlikadani** [comment]
Please send me the TabList config.yml and messages.yml file.

**Comment by Xeterios** [comment]
[Tablist Config and Messages File.zip](https://github.com/montlikadani/TabList/files/2130819/Tablist.Config.and.Messages.File.zip)

**Comment by montlikadani** [comment]
When this long error came up, was there a message.yml file already deleted or deleted?

**Comment by Xeterios** [comment]
I didnt really pay attention to that because I have never edited the messages.yml file.

**Comment by montlikadani** [comment]
This mistake has not happened to anyone but I fix it. This error is about not finding the messages.yml file.

**Comment by montlikadani** [comment]
_**This bug has been fixed in this version:**_ https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=231290
