### ISSUE TITLE
FieldAccessException: Field index 0 is out of bounds for length 0

### ISSUE THREAD

**Issue by Madscience763** [montlikadani/TabList#373]
### Type of bug

Performance loss or memory leak

### TabList version

TabList version 5.6.6 An ultimate animated tablist Author: montlikadani

### Software version

Current: git-Purpur-1876 (MC: 1.19.3)* Previous: git-Purpur-1858 (MC: 1.19.2) * You are running the latest version

### Relevant plugins

Protocollib 5.0.0-SNAPSHOT-b608, PlaceholderAPI 2.11.2

### Console error (if applicable)

[12:34:26 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[12:34:26 WARN]:        at TabList-bukkit-5.6.6.jar//hu.montlikadani.tablist.ProtocolPackets.onPacketSending(ProtocolPackets.java:53)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[12:34:26 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[12:34:26 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[12:34:26 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[12:34:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2248)
[12:34:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2234)
[12:34:26 WARN]:        at net.minecraft.server.players.PlayerList.d(PlayerList.java:972)
[12:34:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1598)
[12:34:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:482)
[12:34:26 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[12:34:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[12:34:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[12:34:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### TabList configuration files

https://paste.gg/p/anonymous/006292b11310498abfa8be77a927996a

### Bug description

This only happens on 1.19.3, as soon as a player joins the server it starts putting errors in the server console, the tablist seems to work fine still

**Comment by montlikadani** [comment]
> Performance loss or memory leak

Wrong issue type, and ProtocolLib dependency will be removed in a future release of TabList. Also try out the newest build from [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) page, select the first one and find artifacts.

**Comment by Madscience763** [comment]
Sorry about that, must have changed because I reloaded the page. This does appear to fix the issue
