### ISSUE TITLE
NPE on player connect

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#376]
### Type of bug

Compatibility issue

### TabList version

```
version TabList [10:11:55 INFO]: TabList version 5.6.7
[10:11:55 INFO]: An ultimate animated tablist
[10:11:55 INFO]: Author: montlikadani
```

### Software version

```
[10:12:13 INFO]: This server is running Paper version git-Paper-367 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 51cfcc8)
You are running the latest version
```

### Relevant plugins

n/a

### Console error (if applicable)

On player connect, and every second thereafter:
```
[10:04:31 WARN]: [TabList] Plugin TabList v5.6.7 generated an exception while executing task 13338
java.lang.NullPointerException: Cannot invoke "hu.montlikadani.tablist.tablist.TabText.toComponent()" because the return value of "hu.montlikadani.tablist.utils.variables.Variables.replaceVariables(org.bukkit.entity.Player, hu.montlikadani.tablist.tablist.TabText)" is null
        at hu.montlikadani.tablist.tablist.TabHandler.sendTab(TabHandler.java:263) ~[TabList-5.6.7.jar:?]
        at hu.montlikadani.tablist.tablist.TabManager.lambda$addPlayer$0(TabManager.java:50) ~[TabList-5.6.7.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-367]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-367]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### TabList configuration files

https://whitedog.straight8.com/drops/tl-config.yml
https://whitedog.straight8.com/drops/tl-tablist.yml

### Bug description

On player connect, and every second thereafter, see the error above.

**Comment by montlikadani** [comment]
damn again.. Thats because of the empty footer, I am going to do a hotfix release now
