### ISSUE TITLE
Plugin TabList v5.6.8 generated an exception while executing task 217

### ISSUE THREAD

**Issue by NexusNRI** [montlikadani/TabList#386]
### Type of bug

Error in console

### TabList version

TabList v5.6.8(For Bukkit)

### Software version

This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Relevant plugins

VoidGen, LoginSecurity, PlaceholderAPI, ClearLag, HolographicDisplays, BuycraftX, MessageAnnouncer, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), MOTD, ViaVersion, StaffPlus, ViaBackwards, ViaRewind, ItemEditor, LuckPerms, AnimatedScoreboard, NametagEdit, SkinsRestorer, Vault, PrisonRanksX, Chatty, WorldEdit, PlayerKits, Essentials, AdvancedBan, Multiverse-Core, WorldGuard, BetterTeams, Shopkeepers, ChestCommands, EssentialsChat, EconomyShopGUI, Graves, CustomCrates, BetterRTP, ProtectionStones, CombatLogX, EssentialsSpawn, CoreProtect, RealMines

### Console error (if applicable)

[19:41:51] [Craft Scheduler Thread - 1/WARN]: [TabList] Plugin TabList v5.6.8 generated an exception while executing task 219
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "this.playerConnectionField" is null
        at hu.montlikadani.tablist.packets.LegacyVersion.sendPacket(LegacyVersion.java:151) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:39) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:44) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:198) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:362) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:315) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$1(Groups.java:299) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:3284a-Spigot-3892929-0ab8487]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[19:41:52] [Craft Scheduler Thread - 7/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because the return value of "hu.montlikadani.tablist.packets.LegacyVersion.fieldByNameAndType(java.lang.Class, java.lang.Class, String[])" is null
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.packets.LegacyVersion.findBoardTeamByName(LegacyVersion.java:659)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.unregisterTeam(ReflectionHandled.java:49)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:27)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:44)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:198)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:362)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:315)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$1(Groups.java:299)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:41:52] [Craft Scheduler Thread - 7/WARN]:   at java.base/java.lang.Thread.run(Thread.java:833)

### TabList configuration files

Default Configuration

### Bug description

At no time have I moved absolutely anything from the configuration. It is precisely when I enter the plugin that it begins to fail and spam the error in the console.

**Comment by montlikadani** [comment]
Try the the newest build from [Actions] (https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) select the first one and find Artifacts.
