### ISSUE TITLE
ClassNotFoundException on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#395]
### Type of bug

Error in console

### TabList version

```
> version TabList
[05:52:38 INFO]: TabList version 5.6.8
[05:52:38 INFO]: An ultimate animated tablist
[05:52:38 INFO]: Author: montlikadani
```

### Software version

```
version
[05:51:48] [Server thread/INFO]: This server is running CraftBukkit version 3684-Spigot-41150f3-f770708 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
[05:51:48] [Server thread/INFO]: You are running the latest version
```

### Console error (if applicable)

```
[05:44:34] [Server thread/INFO]: [TabList] Enabling TabList v5.6.8
[05:44:34] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo
[05:44:34] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[05:44:34] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:390)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:381)
[05:44:34] [Server thread/WARN]:        at hu.montlikadani.tablist.utils.reflection.ClazzContainer.classByName(ClazzContainer.java:246)
[05:44:34] [Server thread/WARN]:        at hu.montlikadani.tablist.utils.reflection.ClazzContainer.<clinit>(ClazzContainer.java:35)
[05:44:34] [Server thread/WARN]:        at hu.montlikadani.tablist.packets.LegacyVersion.<init>(LegacyVersion.java:38)
[05:44:34] [Server thread/WARN]:        at hu.montlikadani.tablist.packets.PacketNM.<clinit>(PacketNM.java:17)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:390)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:381)
[05:44:34] [Server thread/WARN]:        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:91)
[05:44:34] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:44:34] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[05:44:34] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[05:44:34] [Server thread/WARN]:        at net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:131)
[05:44:34] [Server thread/WARN]:        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:262)
[05:44:34] [Server thread/WARN]:        at net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55)
[05:44:34] [Server thread/WARN]:        at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
[05:44:34] [Server thread/WARN]:        at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110)
[05:44:34] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[05:44:34] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[05:44:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:841)
[05:44:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:826)
[05:44:34] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:413)
[05:44:34] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389)
[05:44:34] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
[05:44:34] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017)
[05:44:34] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[05:44:34] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[05:44:34] [Server thread/INFO]: [TabList] Hooked PlaceholderAPI version: 2.11.3
[05:44:34] [Server thread/INFO]: ^[[0;33;22m[^[[0;35;22mTab^[[0;31;1mList^[[0;33;22m]^[[0;37;22m >^[[0;32;1m Enabled^[[0;33;22m v5.6.8^[[0;32;1m (80ms)^[[m
[05:44:34] [Server thread/INFO]: ^[[0;36;22mPM ^[[0;37;22m| ^[[0;32;1mThe plugin has been loaded.^[[m
```

### TabList configuration files

```
hook:
  placeholderapi: true
tps-performance-observation-value: -1.0
fake-players:
  enabled: false
  count-fake-players-to-online-players: false
remove-gray-color-from-tab-in-spectator: false
ignore-vanished-players-in-online-players: false
count-vanished-staffs: true
hide-player-from-tab-when-afk: false
hide-players-from-tablist: false
per-world-player-list:
  enabled: false
  world-groups:
    example1:
    - exampleWorld
    - exampleAnotherWorld
    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2
placeholder-format:
  afk-status:
    enable: false
    show-in-right-or-left-side: true
    show-player-group: true
    format-yes: '&7 [AFK]&r '
    format-no: ''
    sort-last: false
  time:
    time-zone: GMT-8:00
    use-system-zone: false
    time-format: mm:HH
    date-format: yyyy-MM-dd
  ping:
    enable: true
    formats:
    - '&a%ping% <= 200'
    - '&6%ping% >= 200'
    - '&c%ping% > 500'
  tps:
    enable: true
    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'
    size: 1
change-prefix-suffix-in-tablist:
  enable: false
  refresh-interval: 4
  disabled-worlds:
    use-as-whitelist: false
    list:
    - myWorldWithUpper
  sync-plugins-groups-with-tablist: true
  hide-group-when-player-vanished: false
  assign-global-group-to-normal: false
  prefer-primary-vault-group: true
  followNameTagVisibility: false
tablist-object-type:
  type: none
  refresh-interval: 3
  custom-value: '%level%'
  disabled-worlds:
  - testingWorld
check-update: false
download-updates: false
logconsole: true
```

### Bug description

- Install Spigot 1.19.4-3684 (any build from 3672 through 3684)
- Install TabList 5.6.8
- Start server
- Read console/log

Same version runs without error on Spigot 1.19.3-3669 (or Paper 1.19.3-448)

**Comment by wtlgo** [comment]
I also experienced the same exact issue on Paper 1.19.4-453 and Spigot 1.19.4-3672.
TabList v5.6.8 downloaded from Spigot marketplace.

**Comment by montlikadani** [comment]
1.19.4 not supported yet, we're waiting for Purpur to release his API

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/1fc5db51c38d9cbd0c45b22d1b0f84d7a9c88ac2

**Comment by SlimeDog** [comment]
TabList-5.6.8-b194 works with Spigot 1.19.4-3684. Thanks.
