### ISSUE TITLE
Could not pass PlayerQuitEvent to Tablist

### ISSUE THREAD

**Issue by legendcuzican13** [montlikadani/TabList#396]
### Type of bug

Error in console

### TabList version

Tablist version 5.6.7

### Software version

This server is running FlamePaper(1.0.2) for 1.8.8 by LinsaFTW

### Relevant plugins

![Screenshot 2023-03-20 11 10 48 AM](https://user-images.githubusercontent.com/108838775/226401111-f6ff0275-dedf-44f0-b0a8-78d8429833c6.png)

### Console error (if applicable)

```Could not pass event PlayerQuitEvent to TabList v5.6.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:364) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:875) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:315) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:145) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:840) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:678) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:581) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_8_R3.ScoreboardTeam.getName()" because "team" is null
        at hu.montlikadani.v1_8_R3.V1_8_R3.findBoardTeamByName(V1_8_R3.java:276) ~[?:?]
        at hu.montlikadani.v1_8_R3.V1_8_R3.findBoardTeamByName(V1_8_R3.java:40) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.unregisterTeam(ReflectionHandled.java:49) ~[?:?]
        at hu.montlikadani.tablist.tablist.groups.Groups.removePlayerGroup(Groups.java:242) ~[?:?]
        at hu.montlikadani.tablist.TabList.onPlayerQuit(TabList.java:450) ~[?:?]
        at hu.montlikadani.tablist.listeners.Listeners.onPlayerLeave(Listeners.java:31) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor418.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[FlamePaper.jar:git-PaperSpigot-e7c34e5f]
        ... 13 more```

### TabList configuration files

https://legendsmp.minecraft.pe/TabList.zip (download link)

### Bug description

I've simply been using TabList and not sure of the steps to reproduce

**Comment by legendcuzican13** [comment]
Okay thanks. I'll see if this issue persists

**Comment by legendcuzican13** [comment]
@montlikadani Alright, seems the other error has dissapeared(or I just have not seen it because it's quite random) but another has also come along:

``[15:34:24] [Craft Scheduler Thread - 3640/WARN]: Exception in thread "Craft Scheduler Thread - 3640"
[15:34:24] [Craft Scheduler Thread - 3640/WARN]: org.apache.commons.lang.UnhandledException: Plugin TabList v5.6.9 generated an exception while executing task 1798386
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException```

**Comment by montlikadani** [comment]
That exception is half cut which I can't identify

**Comment by legendcuzican13** [comment]
![image](https://user-images.githubusercontent.com/108838775/226703939-2302ffec-c1e9-4613-8869-29864ff1ed0b.png)

**Comment by legendcuzican13** [comment]
Sorry about that, there's a full ss

**Comment by legendcuzican13** [comment]
Also looks like the original error is persisting too

**Comment by montlikadani** [comment]
Those exceptions still half cut, consider sending the log from start to end to pastebin.com

**Comment by legendcuzican13** [comment]
Sorry about that, ill do that now then

**Comment by legendcuzican13** [comment]
Here's the full log. https://legendsmp.minecraft.pe/latest.log

**Comment by montlikadani** [comment]
The exception here is really interesting
```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_8_R3.ScoreboardTeam.getName()" because "team" is null
	at hu.montlikadani.v1_8_R3.V1_8_R3.findBoardTeamByName(V1_8_R3.java:280)
	at hu.montlikadani.v1_8_R3.V1_8_R3.findBoardTeamByName(V1_8_R3.java:40)
	at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.unregisterTeam(ReflectionHandled.java:49)
	at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.registerTeam(ReflectionHandled.java:27)
	at hu.montlikadani.tablist.tablist.groups.impl.ReflectionHandled.setTeam(ReflectionHandled.java:44)
	at hu.montlikadani.tablist.tablist.groups.Groups.setPlayerTeam(Groups.java:198)
	at hu.montlikadani.tablist.tablist.groups.Groups.sortPlayers(Groups.java:354)
	at hu.montlikadani.tablist.tablist.groups.Groups.updatePlayers(Groups.java:307)
	at hu.montlikadani.tablist.tablist.groups.Groups.lambda$startTask$1(Groups.java:291)
```
that `team` never can be null but somehow it is

Did you tried to use spigot 1.8 instead of Flamepaper?

**Comment by legendcuzican13** [comment]
Hmm, that's funny. Now that I can think of it scoreboards have been the root of some other issues too. I'll try using spigot 1.8. Thanks for the help!

**Comment by legendcuzican13** [comment]
If you dont mind ill also delete that log file post up there.

**Comment by legendcuzican13** [comment]
Fixed after switching to pandaspigot
