### ISSUE TITLE
Newest Build Generates Index Out of Bounds Exceptions

### ISSUE THREAD

**Issue by CollinHerber** [montlikadani/TabList#4]
Here is my Config File: https://hastebin.com/sikexaqihe.bash

Here is my Messages File: https://hastebin.com/fequzuvozo.coffeescript

The log file does not have anything error related in it since I deleted from the previous version installed. Only PlaceHolder API Hooked messages.

```[15:46:23 WARN]: [TabList] Plugin TabList v1.9 generated an exception while executing task 1313
java.lang.IndexOutOfBoundsException: Index: 9, Size: 8
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_161]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_161]
        at hu.montlikadani.TabList.TabList$8.run(TabList.java:705) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]```

**Comment by CollinHerber** [comment]
From what I can see without the source my guess is you don't have a length -1 to match the index within your code.

I'm sure you're aware, but length will always be index + 1

**Comment by CollinHerber** [comment]
Something to note btw; The Tablist seems to work even while this exception is generated

**Comment by montlikadani** [comment]
@CollinHerber 
I do not share the source code because there are people who view and use it in their own code so that this plugin will also be lost.
I know the mistake already.

**Comment by montlikadani** [comment]
@CollinHerber 
I've fixed it for work, you can now test it out exceptionally: http://www.mediafire.com/file/uqm7mmqsgcct4po/TabList+Test.jar

**Comment by CollinHerber** [comment]
Been quite busy at work this week. Just put the build on my production server and have yet to see that error.

I will report within 24 hours of working condition.

**Comment by montlikadani** [comment]
I think I fixed it.

**Comment by montlikadani** [comment]
_This error has been resolved and the update is complete._ https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=214894
