### ISSUE TITLE
Could not pass event

### ISSUE THREAD

**Issue by NetyTV** [montlikadani/TabList#44]
I've added your plugin to my plugin folder and started server. (There is no tablist plugin out of this) After the start there's this error (below)

Version: 3.1.
Craftbukkit 1.8.

### Console error (required)

```
[20:42:34 ERROR]: Could not pass event PlayerJoinEvent to TabList v3.1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[minecraft_server.jar:git-Bukkit-ee6d0fa]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Bukkit-ee6d0fa]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:258) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:142) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:81) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:150) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.ServerConnection.c(SourceFile:151) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:733) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [minecraft_server.jar:git-Bukkit-ee6d0fa]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
at hu.montlikadani.TabList.bukkit.TabList.unset(TabList.java:1076) ~[?:?]
at hu.montlikadani.TabList.bukkit.TabList.cancelGroupUpdate(TabList.java:869) ~[?:?]
at hu.montlikadani.TabList.bukkit.TabList.updateGroup(TabList.java:862) ~[?:?]
at hu.montlikadani.TabList.bukkit.TabList.updateAll(TabList.java:771) ~[?:?]
at hu.montlikadani.TabList.bukkit.Listeners.onPlJoin(Listeners.java:35) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[minecraft_server.jar:git-Bukkit-ee6d0fa]
... 14 more
```

Then during the time I am getting this error:
```
[20:44:04 WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
[20:44:04 WARN]: at hu.montlikadani.TabList.bukkit.TabTitle.sendTabTitle(TabTitle.java:52)
[20:44:04 WARN]: at hu.montlikadani.TabList.bukkit.TabList.unregisterTab(TabList.java:780)
[20:44:04 WARN]: at hu.montlikadani.TabList.bukkit.Commands.onCommand(Commands.java:170)
[20:44:04 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:44:04 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[20:44:04 WARN]: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[20:44:04 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:44:04 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609)
[20:44:04 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517)
[20:44:04 WARN]: at `java.lang.Thread.run(Thread.java:745)
```

### Config.yml or other file
Config is in basic settings after first start of plugin

**Comment by montlikadani** [comment]
**_This bug has been fixed in this version:_** https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=239930
