### ISSUE TITLE
[SOLVED]

### ISSUE THREAD

**Issue by Mahdirocks** [montlikadani/TabList#46]
### Describe the bug (required)
The plugin does not work in-game and says it has ran into errors. I looked at the console and the errors bellow were seen.

### Plugin version (required)
v3.2

### Console error (required)
```
27.08 00:20:16 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 0
27.08 00:20:16 [Server] WARN at hu.montlikadani.TabList.bukkit.TabTitle.sendTabTitle(TabTitle.java:52)
27.08 00:20:16 [Server] WARN at hu.montlikadani.TabList.bukkit.TabList$8.run(TabList.java:557)
27.08 00:20:16 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
27.08 00:20:16 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
27.08 00:20:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
27.08 00:20:16 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
27.08 00:20:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

### Config.yml
```
#=========================================#
#                Settings                 #
#=========================================#
# PlaceholderAPI use for the plugin.
placeholderapi: true

# Different playerlist in different world.
per-world-player-list: false

# Remove the NPC name from the tab?
remove-npc-name-from-tab: false

# Fake players that are on the tab.
enable-fake-players: false

# Used for %time% placeholder.
# Formats/examples: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
time-format: 'dd/MM/yyyy'

# Custom variables.
# Unlimited variables.
# Use: <something>: '&6Message...'
custom-variables:
  <name>: '&5&o%player%'
  <lines>: '&5&m======================'

# Enables to change prefix & suffix in player tablist.
# WARNING! Overwrites the tabname function.
change-prefix-suffix-in-tablist:
  enable: false
  # Refresh interval in seconds.
  refresh-interval: 30
  # Hide name tag visibility of the player.
  # This only works if the changing-type scoreboard.
  # Types: always, hide_for_other_teams, hide_for_own_team, never
  name-tag-visibility: always
  # WARNING! You can only change it to false if you experience a problem by changing the group prefix and suffix.
  use-external-scoreboard: true
  # Changing type.
  # Types:
  # scoreboard - Max. character is 16 (if use 1.13 version max. 32) in prefix & suffix.
  # namer - Max. character unlimited.
  changing-type: scoreboard
  # Player name type that will be changed on the tab.
  # Types:
  # name - Player name.
  # displayname - Player display name.
  player-name-type: name

# Tablist objective type.
tablist-object-type:
  enable: false
  # Types:
  # ping - ping of player
  # health - health of player
  # custom - custom value
  type: ping
  # Objective settings.
  object-settings:
    # The ping side next to the player's name indicates the right side.
    ping:
      # Ping update time interval.
      update-interval: 3
      # Which worlds do not show up in ping (world names)?
      disabled-worlds: []
    # The player health (life) the player's name indicates the right side.
    health:
      # Which worlds show your health in tab?
      disabled-worlds:
      - world_the_end
      # Blacklisted players who do not show the icon beside the player's name in the tab.
      blacklisted-players:
      - exampleplayer
      - players
    # Any placeholder can be used, for example, the player level.
    custom:
      custom-value: "%player_level%"
      # Refresh interval.
      refresh-interval: 3
      # Which worlds do not show the custom value setting (world names)?
      disabled-worlds: []

# Player tab name.
tabname:
  # Allow to change player tab name.
  # Warning if this is false, the command will not be registered either. Requires server restart!
  enable: false
  # How many letters should be allowed?
  max-name-length: 200
  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false
  # Enables color coding for tab names. ("&")
  enable-color-code: true
  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: '&6'
  # Which worlds can not be change the tab name?
  disabled-worlds: []
  # Which names can not be used?
  # WARNING! Color codes are NOT considered in command.
  blacklist-names:
  - tabname
  # Use %name%, %sender%, %newline%, %prefix% placeholder.
  # >> NO supported the PlaceholderAPI! <<
  other-changed-name-message: '&3Your name is changed to&r %name%&3 by&e %sender%&3.'

# Tablist. Header & footer with animation.
# Use \n, %staff-online%, %ip-address%, %level%, %xp%, %mc-version%, %motd%, %ping%, %servername%, %online+1%,
# %max-players%, %online-players%, %server-time%, %server-ram-free%, %server-ram-max%, %server-ram-used% placeholders.
# Use placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols
tablist:
  # Enable the tab? (Header & footer)
  enable: true
  # What world does not display the tab?
  disabled-worlds:
  - lobby
  - hub
  # Blacklisted players, where the player not see the tab.
  blacklisted-players: []
  # Tab update time interval. (In ticks!)
  # Set 0 to disable the tab refresh.
  interval: 10
  header:
    - '&b&lDead Dream Network\n&7    <75>&c W <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&6&lDead Dream Network\n&7    <75>&c We <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&4&lDead Dream Network\n&7    <75>&c Wel <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&9&lDead Dream Network\n&7    <75>&c Welc <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&a&lDead Dream Network\n&7    <75>&c Welco <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&e&lDead Dream Network\n&7    <75>&c Welcom <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&5&lDead Dream Network\n&7    <75>&c Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&b&lDead Dream Network\n&7    <75>&6 Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&6&lDead Dream Network\n&7    <75>&7 Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&4&lDead Dream Network\n&7    <75>&4 Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&9&lDead Dream Network\n&7    <75>&a Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&a&lDead Dream Network\n&7    <75>&b Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&e&lDead Dream Network\n&7    <75>&9 Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&5&lDead Dream Network\n&7    <75>&f Welcome <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&b&lDead Dream Network\n&7    <75>&f Welcom <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&6&lDead Dream Network\n&7    <75>&f Welco <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&4&lDead Dream Network\n&7    <75>&f Welc <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&9&lDead Dream Network\n&7    <75>&f Wel <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&a&lDead Dream Network\n&7    <75>&f We <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&e&lDead Dream Network\n&7    <75>&f W <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&5&lDead Dream Network\n&7    <75>&f  <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
    - '&b&lDead Dream Network\n&7    <75>&f  <name>&c!&7 <74>\n&6Ping:&a %ping%&7ms\n<lines>'
  footer:
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Website&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&6&o W&f&oebsite&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o W&6&oe&f&obsite&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o We&6&ob&f&osite&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Web&6&os&f&oite&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Webs&6&oi&f&ote&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Websi&6&ot&f&oe&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
    - '<lines>\n<13>&e&l Players:&6 %online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&f&o Websit&6&oe&7:&2 &nhttps://dead-dream-network.enjin.com/&7 <28>'
  # Per world tablist.
  # Unlimited world.
  per-world:
    enable: false
    world_nether:
      header:
        - '&3This is a per world plugin&6 Tab&aList&3.'
      footer:
        - '&6World:&7 %player_world%'
    world:
      header:
        - '&cThis is a per world plugin&6 TabList'
        - '&6This is a per world plugin&3 TabList'
        - '&3This is a per world plugin&a TabList'
        - '&aThis is a per world plugin&7 TabList'
      footer:
        - '&6World:&7 %player_world%'
  # Per player tablist.
  # Unlimited players.
  per-player:
    enable: false
    testplayer:
      header:
        - '&aWelcome&6 %player_name%\n<lines>'
        - '&aWelcome&7 %player_name%\n<lines>'
        - '&aWelcome&c %player_name%\n<lines>'
        - '&aWelcome&f %player_name%\n<lines>'
        - '&aWelcome&e %player_name%\n<lines>'
        - '&aWelcome&a %player_name%\n<lines>'
        - '&aWelcome&5 %player_name%\n<lines>'
        - '&aWelcome&b %player_name%\n<lines>'
      footer:
        - '<lines>'

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TabList plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline%, %prefix% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v3.0&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: tablist.plugininfo
default-can-see-plugin-information: false

# Unknown-command - If more than one word/letter you write to it.
# Example: /tl reload something...
# Use %command% placeholder.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
# >> NO supported the PlaceholderAPI! <<
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'

# DO NOT CHANGE THIS!
config-version: 5
```

**Comment by montlikadani** [comment]
This is a bug and not solved because you used CraftBukkit software so the plugin did not work.

**Thank you for reporting it!**

**Comment by montlikadani** [comment]
_**This bug has been fixed in this version:** https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=241276_
