### ISSUE TITLE
The plugin is unable to start on Paper 1.20.2

### ISSUE THREAD

**Issue by wtlgo** [montlikadani/TabList#461]
### Type of bug

Error in console

### TabList version

TabList version 5.7.4

### Software version

This server is running Paper version git-Paper-234 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f613437)

### Relevant plugins

AdvancedHelp, BedrockPlayerManager, Citizens, CleanroomGenerator, ClearLag, CoreProtect, DiscordSRV, dynmap, eBackup, Essentials, EssentialsProtect, EssentialsSpawn, FarmControl, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GSit, InventoryRollbackPlus, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, PlaceholderAPI, ProtocolLib, Shopkeepers, SmoothTimber, spark, Spartan, TabList, Vault, ViaBackwards, ViaVersion, Votifier, WorldGuard, YamipaPlugin

### Console error (if applicable)

```
[02:17:38] [Server thread/INFO]: [TabList] Enabling TabList v5.7.4
[02:17:38] [Server thread/INFO]: [TabList] Hooked PlaceholderAPI version: 2.11.4
[02:17:38] [DiscordSRV - Initialization/INFO]: [DiscordSRV] [JDA] Login Successful!
[02:17:38] [Server thread/ERROR]: Error occurred while enabling TabList v5.7.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.PlayerConnection.l()" because "player.c" is null
	at net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket$Entry.<init>(ClientboundPlayerInfoUpdatePacket.java:185) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket$Entry.<init>(ClientboundPlayerInfoUpdatePacket.java:182) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket.<init>(ClientboundPlayerInfoUpdatePacket.java:25) ~[paper-1.20.2.jar:git-Paper-234]
	at hu.montlikadani.v1_20_R2.V1_20_R2.newPlayerInfoUpdatePacketAdd(V1_20_R2.java:158) ~[TabList-bukkit-v5.7.4.jar:?]
	at hu.montlikadani.v1_20_R2.V1_20_R2.newPlayerInfoUpdatePacketAdd(V1_20_R2.java:39) ~[TabList-bukkit-v5.7.4.jar:?]
	at hu.montlikadani.tablist.tablist.fakeplayers.FakePlayer.show(FakePlayer.java:110) ~[TabList-bukkit-v5.7.4.jar:?]
	at hu.montlikadani.tablist.tablist.fakeplayers.FakePlayerHandler.load(FakePlayerHandler.java:84) ~[TabList-bukkit-v5.7.4.jar:?]
	at hu.montlikadani.tablist.TabList.onEnable(TabList.java:95) ~[TabList-bukkit-v5.7.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-234]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-234]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-234]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-234]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:17:38] [Server thread/INFO]: [TabList] Disabling TabList v5.7.4
```

### TabList configuration files

https://paste.gg/p/anonymous/655867dd4e2b4106892ace86abd0c3e0

### Bug description

The plugin refuses to start with the console error I provided before.

**Comment by montlikadani** [comment]
I got this issue aswell during test, but I fixed this in this commit: https://github.com/montlikadani/TabList/commit/b099137bb3f5d52fdad5f05d28b043a468303b38

So you can get the newest build and test it.
