### ISSUE TITLE
Error/warn in 1.13.1

### ISSUE THREAD

**Issue by axemwa** [montlikadani/TabList#47]
### Describe the bug (required)
This error shows up and spamms console
### Plugin version (required)
Paper version git-Paper-176 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

### Console error (required)
> 
`[14:27:03 WARN]: java.lang.NoSuchFieldException: a
[14:27:03 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[14:27:03 WARN]:        at hu.montlikadani.TabList.bukkit.TabTitle.sendTabTitle(TabTitle.java:56)
[14:27:03 WARN]:        at hu.montlikadani.TabList.bukkit.TabList$8.run(TabList.java:557)
[14:27:03 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63)
[14:27:03 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:27:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:27:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:27:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:27:03 WARN]: [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues`
>

### Config.yml or other file
Send the config.yml or other file.
(required)
```
config.yml - https://pastebin.com/pDKJRXPN
```

(optional)
```
other file
```

### Screenshots (optional)
Send a few pictures of the problem if you can
![image](https://user-images.githubusercontent.com/37608633/44641464-31fd2700-aa06-11e8-8701-946defe3719d.png)
.

**Comment by montlikadani** [comment]
**Try update to the latest version.**

**Comment by axemwa** [comment]
thanx that fixed it
