### ISSUE TITLE
Kicked by the server for `Internal Exception`

### ISSUE THREAD

**Issue by Nic0las-Ponce** [montlikadani/TabList#485]
### Type of bug

General issue

### TabList version

5.7.5

### Software version

Current: git-Purpur-1985 (MC: 1.19.4)*  Previous: git-Purpur-1632 (MC: 1.18.2)

### Relevant plugins

AureliumMobs, AureliumSkills, BackpacksRemastered, *BossSkin, BuildPaste, CaliComp, ChestShop, Chunky, Citizens, CMILib, CombatWeaponryPlus, ConditionalEvents, CrazyAuctionsPlus, CustomAdvancements, CustomStructures, DungeonsXL, Enchantments_plus, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, GrapplingHook, HolographicDisplays, ItemsXL, Jobs, JukeBox, LibsDisguises, LoginSecurity, LuckPerms, Magic, ModelEngine, Multiverse-Core, MythicMobs, NoteBlockAPI, PickMeUp, PlaceholderAPI, ProtocolLib, PvPManager, Quests, SafeTrade, SkinsRestorer, spark, TabList, TeaksTweaks, Terra, Tweakin, Vault, WorldEdit, WorldGuard

### TabList configuration files

https://paste.gg/p/anonymous/c384b7f8718445d1831399a5be3f5669

### Bug description

I'm getting this error message repitedly when I enter my server
`Internal Exception: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because the return value of "hu.montlikadani.tablist.utils.reflection.ClazzContainer.getActionField()" is null`
Also, this other message shows up sometimes
`Java.Net.SocketException Conection Reset`
I recently updated from Purpur 1.18.2 to Purpur 1.19.4 and before doing that all worked really fine

**Comment by montlikadani** [comment]
There should be a first time error occurred on server startup, send that.

**Comment by Nic0las-Ponce** [comment]
I think this is the only mention of TabList in the whole startup. The host I'm in trims part of the console when there is too much messages but I think this it's all
```
[14:26:14 INFO]: [TabList] Enabling TabList v5.7.5
[14:26:14 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.PacketPlayOutPlayerInfo
[14:26:14 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185)
[14:26:14 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152)
[14:26:14 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[14:26:14 WARN]: at java.base/java.lang.Class.forName0(Native Method)
[14:26:14 WARN]: at java.base/java.lang.Class.forName(Class.java:375)
[14:26:14 WARN]: at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.utils.reflection.ClazzContainer.classByName(ClazzContainer.java:241)
[14:26:14 WARN]: at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.utils.reflection.ClazzContainer.<clinit>(ClazzContainer.java:39)
[14:26:14 WARN]: at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.packets.LegacyVersion.<init>(LegacyVersion.java:44)
[14:26:14 WARN]: at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.packets.PacketNM.<clinit>(PacketNM.java:29)
[14:26:14 WARN]: at java.base/java.lang.Class.forName0(Native Method)
[14:26:14 WARN]: at java.base/java.lang.Class.forName(Class.java:375)
[14:26:14 WARN]: at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.TabList.onEnable(TabList.java:80)
[14:26:14 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[14:26:14 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[14:26:14 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[14:26:14 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[14:26:14 WARN]: at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577)
[14:26:14 WARN]: at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488)
[14:26:14 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643)
[14:26:14 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442)
[14:26:14 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[14:26:14 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[14:26:14 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[14:26:14 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[14:26:14 INFO]: [TabList] Hooked PlaceholderAPI version: 2.11.5
[14:26:14 INFO]: [TabList] v5.7.5 on v1_19_4 (208ms)
```

**Comment by montlikadani** [comment]
The above attached commit hopefully fixes this issue, you can test it by downloading the [latest build](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml)

**Comment by Nic0las-Ponce** [comment]
It seems to work fine now, thank you!
