### ISSUE TITLE
Error executing task 36

### ISSUE THREAD

**Issue by Calais0001** [montlikadani/TabList#493]
### Type of bug

General issue

### TabList version

5.7.5

### Software version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36) You are running the latest version Previous version: git-Paper-431 (MC: 1.19.3)

### Relevant plugins

[04:11:50 INFO]: Bukkit Plugins:
[04:11:50 INFO]:  - AdvancedBan, DiscordSRV, Essentials, EssentialsChat, floodgate, Geyser-Spigot, ProtocolLib, SkinsRestorer, TabList, Themis
[04:11:50 INFO]:  ViaBackwards, ViaVersion

### Console error (if applicable)

[04:11:53 WARN]: [TabList] Plugin TabList v5.7.5 generated an exception while executing task 36
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R3/entity/CraftPlayer
        at hu.montlikadani.v1_19_3.v1_19_3.getPlayerHandle(v1_19_3.java:110) ~[TabList-bukkit-v5.7.5.jar:?]
        at hu.montlikadani.v1_19_3.v1_19_3.sendPacket(v1_19_3.java:50) ~[TabList-bukkit-v5.7.5.jar:?]
        at hu.montlikadani.tablist.Objects.update(Objects.java:171) ~[TabList-bukkit-v5.7.5.jar:?]
        at hu.montlikadani.tablist.Objects.lambda$startTask$2(Objects.java:145) ~[TabList-bukkit-v5.7.5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-448]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer
        ... 10 more

### TabList configuration files

https://paste.gg/p/anonymous/f9edbbdc2ce643c8b9ba3d5d368ad2a7

### Bug description

I've updated all my plugins including the jar spigot. I only just noticed this but am unsure what to do with it. 

This is probably something as simple as the tablist being incompatible with the latest version of spigot I'm using, I don't know.

**Comment by montlikadani** [comment]
This was already fixed in our latest builds, https://github.com/montlikadani/TabList/actions/workflows/gradle.yml
Select the first one and find artifacts

**Comment by Calais0001** [comment]
@montlikadani Hey, I've just switched to version 5.6.8 and the issue has stopped.

I'm only just seeing your response now, I'll check it out.  Is this a couple builds ahead of the Public 5.7.5 version?

**Comment by montlikadani** [comment]
> I'm only just seeing your response now, I'll check it out. Is this a couple builds ahead of the Public 5.7.5 version?

Yes, a new build after release

**Comment by Calais0001** [comment]
@montlikadani Alright, thank you for your response. 

I understand that while this is a totally different issue, I feel it still pertains to this issue. I have a new error in console that i can't seem to remedy, one that has arisen from this build which fixed my previous issue. 

I'll send the error here as it's quite simple, let me know your thoughts.

```diff
- [Tue 06:33:03 ERROR DiscordSRV] DiscordSRV encountered an unknown Discord error: 50035: Invalid Form Body
topic
	- CHANNEL_TOPIC_INVALID: Channel topic contains at least one word that is not allowed.
```
Fix attempts:
- Checked all channels for blocked words (note: server is discoverable so it'd either be blocked or removed from discovery).
- Perhaps related to AutoMod? I use it.
- The bot I'm using is in 2 servers. Both were checked, alas no luck. 
- Tried removing my custom channel description powered by DiscordSRV that shows server stats.

Thanks for reading.

**Comment by Calais0001** [comment]
Please note that this new issue is from the latest build you sent me here.

**Comment by montlikadani** [comment]
I didn't changed anything related to this, and I doubt it would have any conflicting issue when using NMS packets. The only thing that might happen is creating a FakeConnection when creating a fake player, but since you're on version 1.19 it doesn't affect you, it's been there since 1.20.2.

Googling out this [discord error code](https://www.google.com/search?q=Discord+error%3A+50035), it's more like a bad request of the form body. Since I don't know how DiscordSRV works, that's all I can say.
