### ISSUE TITLE
Updated to 1.19.4 and plugin stopped working

### ISSUE THREAD

**Issue by Calais0001** [montlikadani/TabList#494]
### Type of bug

Error in console

### TabList version

5.7.5

### Software version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4) You are running the latest version Previous version: git-Paper-448 (MC: 1.19.3)

### Relevant plugins

![image](https://github.com/montlikadani/TabList/assets/42801056/81bddf0f-02ba-4769-bc7c-9bcd9a966126)

### Console error (if applicable)

```
[22:31:32 WARN]: [TabList] Plugin TabList v5.7.5 generated an exception while executing task 28
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.getParameterCount()" because the return value of "hu.montlikadani.tablist.utils.reflection.ClazzContainer.getFirstScoreboardObjectiveConstructor()" is null
        at hu.montlikadani.tablist.packets.LegacyVersion.createObjectivePacket(LegacyVersion.java:631) ~[TabList-bukkit-v5.7.5.jar:?]
        at hu.montlikadani.tablist.Objects.update(Objects.java:167) ~[TabList-bukkit-v5.7.5.jar:?]
        at hu.montlikadani.tablist.Objects.lambda$startTask$2(Objects.java:145) ~[TabList-bukkit-v5.7.5.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-550]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

```
[22:30:28 INFO]: [TabList] Enabling TabList v5.7.5
[22:30:28 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.PacketPlayOutPlayerInfo
[22:30:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[22:30:28 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[22:30:28 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[22:30:28 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[22:30:28 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[22:30:28 WARN]:        at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.utils.reflection.ClazzContainer.classByName(ClazzContainer.java:241)
[22:30:28 WARN]:        at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.utils.reflection.ClazzContainer.<clinit>(ClazzContainer.java:39)
[22:30:28 WARN]:        at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.packets.LegacyVersion.<init>(LegacyVersion.java:44)
[22:30:28 WARN]:        at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.packets.PacketNM.<clinit>(PacketNM.java:29)
[22:30:28 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[22:30:28 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[22:30:28 WARN]:        at TabList-bukkit-v5.7.5.jar//hu.montlikadani.tablist.TabList.onEnable(TabList.java:80)
[22:30:28 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[22:30:28 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[22:30:28 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[22:30:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[22:30:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[22:30:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[22:30:28 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[22:30:28 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[22:30:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[22:30:28 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[22:30:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[22:30:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

### TabList configuration files

https://paste.gg/p/anonymous/72aba72872a148529e2ea490d1fb8f0e

### Bug description

We've just updated our paper server version from 1.19.3-448 to 1.19.4-550 and this new error popped up and the plugin stopped working. I updated from 5.6.8 to latest and it didn't fix the problem.

**Comment by Calais0001** [comment]
We've fixed the issue
