### ISSUE TITLE
Paper 1.20.6 compatibility

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#510]
### Type of bug

Compatibility issue

### TabList version

```
version TabList
[10:52:57 INFO]: TabList version 5.7.5
[10:52:57 INFO]: An alternative tablist plugin to replace vanilla empty tab [10:52:57 INFO]: Author: montlikadani
```

### Software version

```
version [10:52:22 INFO]: This server is running Paper version git-Paper-47 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 21d91ce)
You are running the latest version
```

### Relevant plugins

N/A

### Console error (if applicable)

```
[10:40:08] [Paper Plugin Remapper Thread - 0/INFO]: [PluginRemapper] Remapping plugin 'plugins/TabList-5.7.5-b330.jar'...
[10:40:09] [Paper Plugin Remapper Thread - 0/INFO]: [PluginRemapper] Done remapping plugin 'plugins/TabList-5.7.5-b330.jar' in 613ms.
[10:40:42] [Server thread/INFO]: [TabList] Loading server plugin TabList v5.7.5
...
[10:41:08] [Server thread/INFO]: [TabList] Enabling TabList v5.7.5
[10:41:08] [Server thread/ERROR]: Error occurred while enabling TabList v5.7.5 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at TabList-5.7.5-b330.jar/hu.montlikadani.tablist.utils.Util.legacyNmsVersion(Util.java:42) ~[TabList-5.7.5-b330.jar:?]
        at TabList-5.7.5-b330.jar/hu.montlikadani.tablist.TabList.onEnable(TabList.java:65) ~[TabList-5.7.5-b330.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-47]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-47]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-47]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[10:41:08] [Server thread/INFO]: [TabList] Disabling TabList v5.7.5
[10:41:08] [Server thread/ERROR]: Error occurred while disabling TabList v5.7.5
java.lang.NullPointerException: Cannot invoke "hu.montlikadani.tablist.tablist.groups.Groups.cancelUpdate()" because "this.groups" is null
        at TabList-5.7.5-b330.jar/hu.montlikadani.tablist.TabList.onDisable(TabList.java:116) ~[TabList-5.7.5-b330.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:git-Paper-47]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-47]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-47]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-47]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### TabList configuration files

https://paste.gg/p/anonymous/a2ce9ed360b54b9d9e12b6d5e0316f9c

### Bug description

Probably devs are aware that compatibility with Paper 1.20.6 will require changes, but there is no issue posted yet, so here it is.

**Comment by jurohn** [comment]
Confirm

**Comment by SlimeDog** [comment]
This may be helpful...

Per this from Paper developers
```
Once again, please also see the following forum post to make sure your plugins don't break: <https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/>
```
note that with the test Paper server `paper-paperclip-1.20.4-R0.1-SNAPSHOT-mojmap.jar`
```
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/FancyHolograms-2.0.6.66.jar'
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/FancyHolograms-2.0.6.66.jar'
```
Recommended fixes are described in the cited post: [https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/](https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/)

**Comment by montlikadani** [comment]
The above attached commit makes TL boot up, but some features won't work at the moment:
- Numbered objectives (ping, custom) throws exception and kicks players from the server
- Fake players may not work
- TL may not boot up on legacy versions (1.8, 1.12 etc..)

Test jar is available from https://github.com/montlikadani/TabList/actions/workflows/gradle.yml (first build)

**Comment by SlimeDog** [comment]
On my minimally-demanding server, player name and prefix are displayed. Placeholders are not. No console/log errors.

**Comment by montlikadani** [comment]
> Placeholders are not

Which placeholders don't work?

**Comment by SlimeDog** [comment]
Here is the meat of `tablist.yml`
```
header:
- '&7server: %server_name%'
- '&7world: %multiverse_world_alias%'
# '&7region: %coordinatetool_file%'
- '&7loc: %player_x% %player_y% %player_z%'
# '&7biome: %biomeremap_biome_name%'
# '&7hydration: %thirst_level%/100'
- '&7point$: %vault_eco_balance%'
- "&7--------------------"
```
None of the PAPI placeholders were parsed. All PAPI placeholders parsed correctly outside of TabList.

**Comment by montlikadani** [comment]
New build available to fix this, https://github.com/montlikadani/TabList/actions/workflows/gradle.yml

**Comment by SlimeDog** [comment]
All PAPI placeholders (that I use) are parsed now. The world-specific tablist was not detected.
```
per-world:
  world_lobby:
    header:
      - '&7server: %server_name%'
      - '&7world: %multiverse_world_alias%'
    footer:
      # '&7--------------------'
  world_westeros:
    header:
      - '&7server: %server_name%'
      - '&7world: %multiverse_world_alias%'
      - '&7loc: %player_x% %player_y% %player_z%'
      - '&7--------------------'
    footer:
      # '&7--------------------'
  world_skyblock:
    header:
      - '&7server: %server_name%'
      - '&7world: %multiverse_world_alias%'
      - '&7region: %coordinatetool_file%'
      - '&7loc: %player_x% %player_y% %player_z%'
      - '&7biome: %biomeremap_biome_name%'
      - '&7hydration: %thirst_level%/100'
      - '&7point$: %vault_eco_balance%'
      - '&7island level: %Level_bskyblock_island_level%'
      - '&7--------------------'
      - ```

**Comment by Strongis13** [comment]
> New build available to fix this, https://github.com/montlikadani/TabList/actions/workflows/gradle.yml

Using this build, I get kicked from the server when attempting to modify a scoreboard team's color via in-game command

```
[15:10:53] [Server thread/INFO]: Strongis13 issued server command: /team modify Quillmark color blue
[15:10:53] [Server thread/INFO]: [Strongis13: Updated the color for team [Quillmark] to blue]
[15:10:53] [Server thread/INFO]: Strongis13 lost connection: Internal Exception: java.util.NoSuchElementException
```
There are no other plugins on the server, and removing TabList fixes this issue

**Comment by jurohn** [comment]
https://codeshare.io/WLmXW8

Using the second-last version.
Kicks me out when connection while both tablist and gsit using the same package??

**Comment by montlikadani** [comment]
> All PAPI placeholders (that I use) are parsed now. The world-specific tablist was not detected.

I am unable to reproduce this

**Comment by montlikadani** [comment]
New build available to fix these, https://github.com/montlikadani/TabList/actions/workflows/gradle.yml

> I get kicked from the server when attempting to modify a scoreboard team's color via in-game command
> 
> ```
> [15:10:53] [Server thread/INFO]: Strongis13 issued server command: /team modify Quillmark color blue
> [15:10:53] [Server thread/INFO]: [Strongis13: Updated the color for team [Quillmark] to blue]
> [15:10:53] [Server thread/INFO]: Strongis13 lost connection: Internal Exception: java.util.NoSuchElementException
> ```
> 
> There are no other plugins on the server, and removing TabList fixes this issue



> https://codeshare.io/WLmXW8
> 
> Using the last gradle version. Kicks me out when connection while both tablist and gsit using the same package??

**Comment by jurohn** [comment]
> New build available to fix these, https://github.com/montlikadani/TabList/actions/workflows/gradle.yml
> 
> > I get kicked from the server when attempting to modify a scoreboard team's color via in-game command
> > ```
> > [15:10:53] [Server thread/INFO]: Strongis13 issued server command: /team modify Quillmark color blue
> > [15:10:53] [Server thread/INFO]: [Strongis13: Updated the color for team [Quillmark] to blue]
> > [15:10:53] [Server thread/INFO]: Strongis13 lost connection: Internal Exception: java.util.NoSuchElementException
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There are no other plugins on the server, and removing TabList fixes this issue
> 
> > https://codeshare.io/WLmXW8
> > Using the last gradle version. Kicks me out when connection while both tablist and gsit using the same package??

https://codeshare.io/k07J9M

Not fixed
Might be because of ProtocolLib tho, that messes with 3 of my other plugins as well. But without tablist this error doesnt appear.

**Comment by montlikadani** [comment]
> Not fixed Might be because of ProtocolLib tho, that messes with 3 of my other plugins as well. But without tablist this error doesnt appear.
> 
> 19.05 10:26:14 [Disconnect] User 6lies has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_score'

Now I removed the BLANK number format from tablist objectives, since this type is like when you disable objectives at all, looks like this was the issue, https://github.com/montlikadani/TabList/actions/workflows/gradle.yml

**Comment by jurohn** [comment]
> > Not fixed Might be because of ProtocolLib tho, that messes with 3 of my other plugins as well. But without tablist this error doesnt appear.
> > 19.05 10:26:14 [Disconnect] User 6lies has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_score'
> 
> Now I removed the BLANK number format from tablist objectives, since this type is like when you disable objectives at all, looks like this was the issue, https://github.com/montlikadani/TabList/actions/workflows/gradle.yml

I confirm this fixed it. Thank you

**Comment by adydetra** [comment]
On Aternos, `1.20.6` | `Paper` | `TabList v5.7.5`

![image](https://github.com/montlikadani/TabList/assets/108399634/0ff63f90-89dc-4ebb-a76e-355469167289)

```
[21:11:36] [Server thread/INFO]: [TabList] Enabling TabList v5.7.5
[21:11:36] [Server thread/ERROR]: Error occurred while enabling TabList v5.7.5 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at TabList-bukkit-v5.7.5.jar/hu.montlikadani.tablist.utils.Util.legacyNmsVersion(Util.java:42) ~[TabList-bukkit-v5.7.5.jar:?]
	at TabList-bukkit-v5.7.5.jar/hu.montlikadani.tablist.TabList.onEnable(TabList.java:65) ~[TabList-bukkit-v5.7.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:11:36] [Server thread/INFO]: [TabList] Disabling TabList v5.7.5
[21:11:36] [Server thread/ERROR]: Error occurred while disabling TabList v5.7.5
java.lang.NullPointerException: Cannot invoke "hu.montlikadani.tablist.tablist.groups.Groups.cancelUpdate()" because "this.groups" is null
	at TabList-bukkit-v5.7.5.jar/hu.montlikadani.tablist.TabList.onDisable(TabList.java:116) ~[TabList-bukkit-v5.7.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-112-347bbe3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by SlimeDog** [comment]
This issue seems to be resolved in later releases. Thanks.
