### ISSUE TITLE
Console error when player joins

### ISSUE THREAD

**Issue by nexlemav** [montlikadani/TabList#52]
```
[00:01:50 WARN]: java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabListAPI/master/plugin.yml
[00:01:50 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[00:01:50 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[00:01:50 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[00:01:50 WARN]:        at java.net.URL.openStream(Unknown Source)
[00:01:50 WARN]:        at hu.montlikadani.TabList.bukkit.Listeners.onPlJoin(Listeners.java:79)
[00:01:50 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:01:50 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:01:50 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:01:50 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[00:01:50 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[00:01:50 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:01:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[00:01:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[00:01:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[00:01:50 WARN]:        at java.lang.Thread.run(Unknown Source)
[00:01:50 WARN]: [TabList] Failed to compare versions. java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabListAPI/master/plugin.yml Please report it here:
https://github.com/montlikadani/TabListAPI/issues
```

**Comment by montlikadani** [comment]
**Uh, I'm sorry for this. I'm fixing this bug.**

**Comment by vergara2090** [comment]
I have the same error ;)

**Comment by montlikadani** [comment]
_**Fixed, please update:**_ https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=245089
