### ISSUE TITLE
Error shown in console whenever a player joins (FileNotFoundException)

### ISSUE THREAD

**Issue by MattPuffin** [montlikadani/TabList#55]
### Describe the bug (required)
Error shown in console whenever a player joins

### Software (Bukkit/Spigot) version (required)
Spigot 1.13.1
### Console error (required)
[15:02:01 WARN]: java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabListAPI/master/plugin.yml
[15:02:01 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[15:02:01 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[15:02:01 WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[15:02:01 WARN]: 	at java.net.URL.openStream(Unknown Source)
[15:02:01 WARN]: 	at hu.montlikadani.TabList.bukkit.Listeners.onPlJoin(Listeners.java:79)
[15:02:01 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:02:01 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:02:01 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:02:01 WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:02:01 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[15:02:01 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:02:01 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:02:01 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[15:02:01 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[15:02:01 WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:02:01 WARN]: [TabList] Failed to compare versions. java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabListAPI/master/plugin.yml Please report it here:
https://github.com/montlikadani/TabListAPI/issues

### Config.yml or other file
Send the config.yml or other file.
You can send (if you want) files link e.g. pastebin.com or paste a code block.
(required)
https://pastebin.com/KGLDSTff

### Screenshots (optional)
![tablist error](https://user-images.githubusercontent.com/43544578/45958391-40436080-c00f-11e8-9e88-7e0c3e1f8f18.png)

**Comment by montlikadani** [comment]
**Please update to the latest version.**
