### ISSUE TITLE
Bungeecord error?

### ISSUE THREAD

**Issue by Zsomi** [montlikadani/TabList#66]
```
task=hu.montlikadani.tablist.bungee.TabList$2@315f43d5, delay=0, period=180, running=true) encountered an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at hu.montlikadani.tablist.bungee.TabList.getTablist(TabList.java:223)
at hu.montlikadani.tablist.bungee.TabList.access$7(TabList.java:174)
at hu.montlikadani.tablist.bungee.TabList$2.run(TabList.java:164)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
> 22:13:57 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@71e9ebae, id=1, owner=hu.montlikadani.tablist.bungee.TabList@52d239ba,
```

**Comment by montlikadani** [comment]
@Zsomi 
Please send me a bungeeconfig.yml file.

_Please do not copy and paste all the bugs that the console will cause, as there are only 11 lines of error._

**Comment by Zsomi** [comment]
Nem tudnànk ezt discordon megbeszèlni
