### ISSUE TITLE
Failed to compare versions.

### ISSUE THREAD

**Issue by xenforq** [montlikadani/TabList#76]
### Describe the bug
This issue keeps occuring and ends up slowing my startup/restart times. It keeps outputting in console when server is either reloaded, restarted, or booting.  

### Software (Bukkit/Spigot/Paper) name & version: 
Running git-Paper-495.
> This server is running Paper version git-Paper-495 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-> SNAPSHOT)

### Plugin version: 
3.9

### Java version: 
> Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

### Console error
> [20:20:38 WARN]: [TabList] Found outdated configuration (config.yml)! (Your version: 8 | Newest version: 9)
[20:20:38 WARN]: [TabList] Found outdated configuration (messages.yml)! (Your version: 4 | Newest version: 5)
[20:20:58 WARN]: java.net.UnknownHostException: raw.githubusercontent.com
[20:20:58 WARN]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[20:20:58 WARN]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[20:20:58 WARN]: at java.net.Socket.connect(Socket.java:589)
[20:20:58 WARN]: at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[20:20:58 WARN]: at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[20:20:58 WARN]: at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[20:20:58 WARN]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[20:20:58 WARN]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[20:20:58 WARN]: at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[20:20:58 WARN]: at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[20:20:58 WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[20:20:58 WARN]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[20:20:58 WARN]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[20:20:58 WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[20:20:58 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[20:20:58 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[20:20:58 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[20:20:58 WARN]: at java.net.URL.openStream(URL.java:1045)
[20:20:58 WARN]: at hu.montlikadani.tablist.TabList.checkVersion(TabList.java:291)
[20:20:58 WARN]: at hu.montlikadani.tablist.TabList.onEnable(TabList.java:112)
[20:20:58 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[20:20:58 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[20:20:58 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:20:58 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[20:20:58 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[20:20:58 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[20:20:58 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[20:20:58 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[20:20:58 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[20:20:58 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[20:20:58 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:20:58 WARN]: [TabList] Failed to compare versions. java.net.UnknownHostException: raw.githubusercontent.com
>

### Config.yml
Send the config.yml or other file.
You can send files link e.g. [pastebin.com](https://pastebin.com/) or paste a code block.
```
config.yml
#=================================OOO====================================#
#                     TabList Configuration File                         #
#=================================OOO====================================#
# config.yml file. Plugin version: 3.8                                   #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configuration]                                                #
# https://github.com/montlikadani/TabList/blob/master/config.yml         #
#                                                                        #
# [Placeholders]                                                         #
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/             #
#                                                                        #
# [Other placeholders]                                                   #
# https://github.com/montlikadani/TabList/wiki/Placeholders              #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - If you find a bug, send here:                                        #
# https://github.com/montlikadani/TabList/issues                         #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/TabList/wiki/Symbols                   #
# - If the string is empty does not send the message.                    #
#=================================OOO====================================#

# PlaceholderAPI use for the plugin.
placeholderapi: true

# Different playerlist in different world.
per-world-player-list: false

# Remove the NPC name from the tab?
# If the Citizens plugin has installed then this ignoring, because the Citizens has a feature
# to disable the npcs from tab.
remove-npc-name-from-tab: false

# Fake players that are on the tab.
enable-fake-players: false

# Formats/examples: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
# Used for %server-time% placeholder.
time-format: "mm:HH"
# Used for %date% placeholder.
date-format: "dd/MM/yyyy"

# Ping color format for %ping% placeholder.
ping-placeholder-format:
  enable: true
  # Use color coding "&" for color.
  good-ping:
    color: "&a"
    amount: 200
  medium-ping:
    color: "&6"
    amount: 500
  bad-ping: "&c"

# Custom variables with unlimited variables.
# Use: <something>: "&6Message..."
custom-variables:
  <name>: "&5&o%player_name%"
  <lines>: "&5&m======================"

# Enables to change prefix & suffix in player tablist.
# WARNING! Overwrites the tabname function.
change-prefix-suffix-in-tablist:
  enable: true
  # Refresh interval in seconds.
  # Set to 0 if you don't want to refresh the groups.
  # If 0 you will required to execute the /tl rl command, to reload the groups.
  refresh-interval: 30
  # Hide player group in tablist when the player is vanished?
  # Required Essentials plugin!
  hide-group-when-player-vanished: false
  # Hide player group in tablist when the player is afk?
  # Required Essentials plugin!
  hide-group-when-player-afk: false
  # Use the Essentials nickname instead of groups?
  use-essentials-nickname: false
  # Hide name tag visibility of the player.
  # This only works if the changing-type scoreboard.
  # Types: always, hide_for_other_teams, hide_for_own_team, never
  name-tag-visibility: always
  # WARNING! You can only change it to false if you experience a problem by changing the group prefix and suffix.
  use-external-scoreboard: true
  # Scoreboard changing types (if you experience some problems by changing group).
  # scoreboard - Max. character is 16 (if use 1.13 version max. 64) in prefix & suffix.
  # namer - Max. character is unlimited.
  changing-type: scoreboard

# Tablist objective types
# Shows your current health (with life indicator), shows your current ping or a custom placeholder
# that shows number.
tablist-object-type:
  enable: false
  # Types:
  # ping - ping of player
  # health - health of player
  # custom - custom value
  type: ping
  # Objective settings
  object-settings:
    # The ping side next to the player's name indicates the right side.
    ping:
      # Ping update time interval in seconds.
      update-interval: 3
      # Which worlds do not show up in ping (world names)?
      disabled-worlds: []
    # The player health (life) the player's name indicates the right side.
    health:
      # Which worlds do not show the players health in tab?
      disabled-worlds:
      - world_the_end
      # Blacklisted players who do not show the health in tab.
      blacklisted-players:
      - exampleplayer
      - players

# Changing player tablist name with unlimited characters.
tabname:
  # Allow to change player tab name.
  # Warning if this is false, the command will not be registered either. Requires server restart!
  enable: true
  # Use the Essentials nickname instead of tab name?
  use-essentials-nickname: true
  # How many letters should be allowed?
  max-name-length: 200
  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false
  # Enables color coding for tab names. ("&")
  enable-color-code: true
  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: "&6"
  # Which worlds can not be change the tab name?
  disabled-worlds: []
  # Which names can not be used?
  blacklist-names:
  - tabname

# Tablist, header & footer with animation.
# Use \n, %staff-online%, %ip-address%, %level%, %xp%, %exp-to-level%, %mc-version%, %motd%, %ping%, %servername%,
# %max-players%, %online-players%, %server-time%, %server-ram-free%, %server-ram-max%, %server-ram-used% placeholders.
# Use placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols
# Use %anim:animationName% placeholder to make an animation.
tablist:
  # Enable the tab? (Header & footer)
  enable: true
  # Hide tab when the player is vanished?
  # Required Essentials plugin!
  hide-tab-when-player-vanished: false
  # What world does not display the tab?
  disabled-worlds:
  - "world1"
  - "worldTest"
  # Blacklisted players, where the player not see the tab.
  blacklisted-players: []
  # Tab update time interval. (In ticks!)
  # Set 0 to disable the tab refresh.
  interval: 4
  header:
    - "&7&m--------------------------------------"
    - "&6&lXen's Resort"
    - "&7"
    - "&7>> &eWelcome to the &6&lXen's Resort Survival &7<<"
    - "&7&m--------------------------------------"
    - "&7"
  footer:
    - "&7"
    - "&7&m--------------------------------------"
    - "&eServer Information:"
    - "&6&lTPS: &f%tps%" 
    - "&6&lRAM: &a%server-ram-used%MB &f/ &c%server-ram-max%MB"
    - "&6&lPing: %ping%ms"
    - "&7&m--------------------------------------"
  # Per world tablist
  per-world:
    enable: false
    # If the world name is not specified, will see the default tab.
    enable-default-tab-if-world-not-specified: true
    world_nether:
      header:
        - "&3This is a per world plugin %anim:tablist%&3."
      footer:
        - "&6World:&7 %player_world%"
    world:
      header:
        - "%anim:perWorld%"
      footer:
        - "&6World:&7 %player_world%"
      # Per player in per world tablist
      per-player:
        enable: false
        # If the player name is not specified, will see the default tab.
        enable-default-tab-if-player-not-specified: true
        playerName:
          header:
            - "&3This is a per player plugin %anim:tablist%&3."
          footer:
            - "&6World:&7 %player_world%"
            - "&aPlayer:&8 %player_name%"
  # Per player tablist
  per-player:
    enable: false
    # If the player name is not specified, will see the default tab.
    enable-default-tab-if-player-not-specified: false
    testplayer:
      header:
        - "%anim:perPlayer%"
      footer:
        - "<lines>"
  # Per group tablist
  # Requires Vault plugin!
  per-group:
    enable: false
    # If the group name is not specified, will see the default tab.
    enable-default-tab-if-group-not-specified: true
    default:
      header:
        - "%anim:perGroupHead%"
      footer:
        - "%anim:perGroupFoot%"

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TabList plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline%, %prefix% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v3.8&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 8
```

**Comment by montlikadani** [comment]
Java does not seem to be able to connect to websites using Scanner. This is a big error because it doesn't send me a similar error since I've been using it.
Have you tried to upgrade Java to 202?

**Comment by montlikadani** [comment]
_Fixed in the latest version._
