### ISSUE TITLE
./tablist reload --> "generated an exception while executing task 3"

### ISSUE THREAD

**Issue by Metatron2012** [montlikadani/TabList#77]
### Describe the bug (!)
first at all, i'm not an english speaker but i need to try it.
To the matter; when I use /tablist reload command (or /tl rl) the plugin never reload and it gives me a lot of errors.
I tried to customize it in the online server, but it never recharged when trying to apply the changes using /tablist reload.
So, I made a local server on my computer with the same "spigot.jar". I put the plugin in the "plugins" folder, I started the server and the first thing I did was to use the "/tablist reload" command. That's what gives me infinite errors

(!) Software (Bukkit/Spigot/Paper) name & version:
(extracted from minecraft's log):

This server is running CraftBukkit version git-Spigot-a1f2566-a4c555b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

(!) Plugin version:

My server is using the Latest version: v4.0

Java version: 8.0.2010.9 (extracted from Windows's Control Panel)

### Console error (!)
This error appears infinite times(extracted from Minecraft's latest.log):

--------------------------------------------------

[15:05:10] [Craft Scheduler Thread - 0/WARN]: [TabList] Plugin TabList v4.0 generated an exception while executing task 3
java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderAPI
	at hu.montlikadani.tablist.TabList.setPlaceholders(TabList.java:1596) ~[?:?]
	at hu.montlikadani.tablist.TabList.replaceVariables(TabList.java:782) ~[?:?]
	at hu.montlikadani.tablist.TabList$8.run(TabList.java:661) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot_1_13_2.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot_1_13_2.jar:git-Spigot-a1f2566-a4c555b]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.PlaceholderAPI
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[Spigot_1_13_2.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[Spigot_1_13_2.jar:git-Spigot-a1f2566-a4c555b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	... 8 more

--------------------------------------------------

### Config.yml (!)

I'm using the default config files. The error appears even without modifying the configs, or "messages.yml", or "animcreator.yml"

**Comment by montlikadani** [comment]
Thanks!
Will be fixed in the next release.

**Comment by Metatron2012** [comment]
Thank you!

**Comment by montlikadani** [comment]
_Fixed in the latest version._
