### ISSUE TITLE
Player placeholders fail

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#83]
Server Java 11.0.3
Spigot 1.14 (2248)
PlaceholderAPI 2.9.2-DEV-61
Expansion-Player 1.6.5
TabList 4.3

Player placeholders parse correctly with PAPI, but do not parse with TabList and generate errors (every trigger). Header is not displayed (I don't display footer), only player list.

No issues with Spigot 1.13.2 final, otherwise same configuration.

### Console error
```
[10:28:00] [Craft Scheduler Thread - 6/WARN]: [TabList] Plugin TabList v4.3 generated an exception while executing task 96
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getServerName()Ljava/lang/String;
        at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:176) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
        at hu.montlikadani.tablist.TabList.setPlaceholders(TabList.java:1433) ~[?:?]
        at hu.montlikadani.tablist.Variables.replaceVariables(Variables.java:67) ~[?:?]
        at hu.montlikadani.tablist.TabList.sendTab(TabList.java:714) ~[?:?]
        at hu.montlikadani.tablist.TabList.access$1(TabList.java:658) ~[?:?]
        at hu.montlikadani.tablist.TabList$1.run(TabList.java:623) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar-2019-05-01-0918:git-Spigot-1eece4f-1fa9a81]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar-2019-05-01-0918:git-Spigot-1eece4f-1fa9a81]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
### Config.yml
filtered to remove comments and blank lines
```
placeholderapi: true
per-world-player-list: false
enable-fake-players: false
ignore-vanished-players-in-online-players: true
hide-player-from-tab-when-afk: false
time-format: 'yyyy-MM-dd HH:mm:ss'
ping-placeholder-format:
  enable: true
  good-ping:
    color: '&a'
    amount: 200
  medium-ping:
    color: '&6'
    amount: 500
  bad-ping: '&c'
custom-variables:
  <name>: '&5&o%player_name%'
  <lines>: '&5&m======================'
change-prefix-suffix-in-tablist:
  enable: false
  refresh-interval: 0
  enable-animation: false
  hide-group-when-player-vanished: false
  hide-group-when-player-afk: false
  use-essentials-nickname: true
  name-tag-visibility: always
  use-external-scoreboard: true
  changing-type: scoreboard
tablist-object-type:
  enable: false
  type: ping
  object-settings:
    ping:
      update-interval: 3
      disabled-worlds: []
    health:
      disabled-worlds: []
      blacklisted-players:
      - exampleplayer
      - players
    custom:
      custom-value: "%player_level%"
      refresh-interval: 3
      disabled-worlds: []
tabname:
  enable: false
  use-essentials-nickname: false
  max-name-length: 200
  clear-player-tabname-on-quit: false
  enable-color-code: true
  default-color:
    enable: false
    color: "&6"
  disabled-worlds: []
  blacklist-names:
  - tabname
tablist:
  enable: true
  hide-tab-when-player-vanished: false
  disabled-worlds:
  - lobby
  blacklisted-players: []
  interval: 4
  header:
    - '&7server: %player_server%\n&7world: %multiverse_world_alias%\n&7loc: %player_x% %player_y% %player_z%\n&7region: %coordinatetool_file%\n&7hydration: %thirst_level%/100\n&7point$: %vault_eco_balance%\n&7==================='
  footer:
    - ''
  per-world:
    enable: true
    enable-default-tab-if-world-not-specified: true
    world_parkour:
      header:
        - '&7server: %player_server%\n&7world: %multiverse_world_alias%\n&7==================='
      footer:
        - ''
    world_skyblock:
      header:
        - '&7server: %player_server%\n&7world: %multiverse_world_alias%\n&7loc: %player_x% %player_y% %player_z%\n&7hydration: %thirst_level%/100\n&7point$: %vault_eco_balance%\n&7level: %bskyblock_level%\n&7==================='
      footer:
        - ''
  per-player:
    enable: false
    enable-default-tab-if-player-not-specified: false
    testplayer:
      header:
        - '%anim:perPlayer%'
      footer:
        - '<lines>'
  per-group:
    enable: false
    enable-default-tab-if-group-not-specified: true
    default:
      header:
        - '%anim:perGroupHead%'
      footer:
        - '%anim:perGroupFoot%'
enabled: true
metrics: false
check-update: false
logconsole: true
plugin-enable: '%prefix% The plugin successfully enabled v4.3!'
plugin-disable: '%prefix% The plugin successfully disabled!'
config-version: 11
```

**Comment by montlikadani** [comment]
It seems this is not the TabList problem, because this error comes to my code which only replaces the PlaceholderAPI placeholders.
The Player expansion on PAPI is using the deprecated version, that the 1.14 does not support anymore. https://github.com/PlaceholderAPI/Player-Expansion/commit/c73bf086e1f3160a21e37ede97035c1efb586384#diff-2a880cd46327aa24610ed2958af2a5c7R176

**Comment by SlimeDog** [comment]
OK. I post [there](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/105). Thanks.

**Comment by SlimeDog** [comment]
Clearly this issue is on the PAPI table. I'll close it when I verify the relevant PAPI update.

**Comment by SlimeDog** [comment]
With updates to PAP Player and Server, confirm that %server_name% is recognized by Spigot 1.13.2 and 1.14, with appropriate configurations.
