### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by xKenn12** [montlikadani/TabList#88]
```
[WARNING] java.lang.NoClassDefFoundError: com.google.gson.JsonElement

[WARNING] at hu.montlikadani.tablist.TabList.onEnable(TabList.java:132)

[WARNING] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)

[WARNING] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)

[WARNING] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)

[WARNING] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341)

[WARNING] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313)

[WARNING] at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394)

[WARNING] at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362)

[WARNING] at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317)

[WARNING] at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190)

[WARNING] at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484)

[WARNING] at java.lang.Thread.run(Thread.java:813)

[WARNING] Caused by:

[WARNING] java.lang.ClassNotFoundException: com.google.gson.JsonElement

[WARNING] at java.net.URLClassLoader.findClass(URLClassLoader.java:591)

[WARNING] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)

[WARNING] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)

[WARNING] at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946)

[WARNING] at java.lang.ClassLoader.loadClass(ClassLoader.java:891)

[WARNING] at java.lang.ClassLoader.loadClass(ClassLoader.java:874)

[WARNING] ... 12 more
```
Help please

**Comment by montlikadani** [comment]
Disable metrics in configuration.

**Comment by xKenn12** [comment]
Thanks

**Comment by xKenn12** [comment]
how can i find %player_name% in tablist? its not finding

**Comment by montlikadani** [comment]
By installing PlaceholderAPI, more info on main site, please read it the main site firstly.

**Comment by xKenn12** [comment]
[WARNING] [TabList] Task #419 for TabList v4.4 generated an exception

java.lang.NoSuchMethodError: org/bukkit/scoreboard/Team.hasEntry(Ljava/lang/String;)Z (loaded from file:/pro/bin/mc/craftbukkit/1.8/craftbukkit-1.8.jar by sun.misc.Launcher$AppClassLoader@6bffb3a9) called from class hu.montlikadani.tablist.TabList (loaded from file:/home/gs-41489/plugins/TabList.jar by org.bukkit.plugin.java.PluginClassLoader@4c9ba96).

at hu.montlikadani.tablist.TabList.setTeam(TabList.java:1064) ~[?:?]

at hu.montlikadani.tablist.TabList.setGroup(TabList.java:985) ~[?:?]

at hu.montlikadani.tablist.TabList.access$2(TabList.java:900) ~[?:?]

at hu.montlikadani.tablist.TabList$4.run(TabList.java:865) ~[?:?]

at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.8.jar:git-Bukkit-7019900]

at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:668) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-7019900]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by montlikadani** [comment]
Should be fixed in the next release.

**Comment by xKenn12** [comment]
thanks

**Comment by montlikadani** [comment]
**Update time...**
