### ISSUE TITLE
Tablist v4.4 is not working on version 1.14.4

### ISSUE THREAD

**Issue by PROZACTv** [montlikadani/TabList#89]
[06:01:40] [Server thread/WARN]: java.lang.NullPointerException
[06:01:40] [Server thread/WARN]:        at hu.montlikadani.tablist.TabList.onDisable(TabList.java:165)
[06:01:40] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[06:01:40] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377)
[06:01:40] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438)
[06:01:40] [Server thread/WARN]:        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:84)
[06:01:40] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:01:40] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[06:01:40] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[06:01:40] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[06:01:40] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[06:01:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[06:01:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[06:01:40] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776)
[06:01:40] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by montlikadani** [comment]
Nop, is working just you disabled the plugin with `enabled` option in config.yml.
