### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by 1vomarek1** [montlikadani/TabList#92]
1vomarek1[/46.135.39.134:46596] logged in with entity id 205 at ([world]-67.62511890519309, 75.65767136311594, 348.92496364687884)
> [14:33:46 WARN]: [TabList] Task #331 for TabList v4.4 generated an exception
java.lang.NoSuchMethodError: org.bukkit.scheduler.BukkitTask.isCancelled()Z
at hu.montlikadani.tablist.TabList.cancelGroupUpdate(TabList.java:895) ~[?:?]
at hu.montlikadani.tablist.TabList.updateGroup(TabList.java:806) ~[?:?]
at hu.montlikadani.tablist.TabList.updateAll(TabList.java:793) ~[?:?]
at hu.montlikadani.tablist.Listeners.lambda$0(Listeners.java:24) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1104]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [patched_1.11.2.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.11.2.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.11.2.jar:git-Paper-1104]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by montlikadani** [comment]
Same https://github.com/montlikadani/TabList/issues/91
Closed, due to duplicate.
