### ISSUE TITLE
Tablist not working after editing config

### ISSUE THREAD

**Issue by NatTheChicken** [montlikadani/TabList#96]
Tablist was working when I uploaded it to my server but I decided to edit the config file a little bit and now i am getting this console error:

```
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:163) ~[craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:131) ~[craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:184) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:159) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at hu.montlikadani.tablist.Listeners.onPlJoin(Listeners.java:43) [TabList.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:506) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:491) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:327) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:147) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:121) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:221) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(SourceFile:171) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:910) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 232, column 3:
      enable: true
      ^
expected <block end>, but found '<scalar>'
 in 'string', line 255, column 6:
      - "<lines>"
         ^
```

Here is my config file as well:
https://pastebin.com/5LWzKLbu

**Comment by NetyTV** [comment]
Check your config formatting. Like here:
- "&7Staff Online: %staff-online%
You don't have " at the end of the line
